# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪地狼

PRESET = {
    "name": "animal_雪地狼",
    "description": "雪地狼",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "majestic wolf", "thick white or grey fur", "piercing yellow eyes", "standing in snowy forest"],
        "scene": ["winter atmosphere", "powerful presence", "wildlife photography"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, domestic, dog"
}
