# Auto-generated by convert_json_to_presets_v2.py
# 描述: 森林狐狸

PRESET = {
    "name": "animal_森林狐狸",
    "description": "森林狐狸",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "beautiful red fox", "clever eyes", "thick fur", "standing in a forest"],
        "scene": ["autumn leaves", "natural lighting", "wildlife photography", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "wild animal"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, captive, zoo"
}
