# Auto-generated by convert_json_to_presets_v2.py
# 描述: 优雅白马

PRESET = {
    "name": "animal_优雅白马",
    "description": "优雅白马",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "beautiful white horse", "flowing mane", "graceful posture", "running in a meadow", "golden sunset"],
        "scene": ["majestic", "ethereal", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "animal photography", "freedom"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, ugly, sick"
}
