# Auto-generated by convert_json_to_presets_v2.py
# 描述: 威风狗狗

PRESET = {
    "name": "animal_威风狗狗",
    "description": "威风狗狗",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "majestic dog", "handsome breed", "shiny coat", "intelligent eyes", "loyal expression"],
        "scene": ["outdoor setting", "natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "pet photography", "energetic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, sick, sad"
}
