# Auto-generated by convert_json_to_presets_v2.py
# 描述: 蝴蝶花卉

PRESET = {
    "name": "animal_蝴蝶花卉",
    "description": "蝴蝶花卉",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "colorful butterflies on blooming flowers", "vibrant wings", "macro photography", "morning dew"],
        "scene": ["garden setting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["nature photography", "delicate"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, dead, wilted"
}
