# Auto-generated by convert_json_to_presets_v2.py
# 描述: 可爱猫咪

PRESET = {
    "name": "animal_可爱猫咪",
    "description": "可爱猫咪",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "adorable cat", "fluffy fur", "big bright eyes", "cute expression"],
        "scene": ["soft lighting", "close-up portrait", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["pet photography", "warm atmosphere"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, scary, angry"
}
