# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫女王

PRESET = {
    "name": "beauty_anime_动漫女王",
    "description": "动漫女王",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime queen", "huge breasts", "wearing revealing royal outfit", "crown", "holding a scepter", "commanding presence"],
        "scene": ["dramatic lighting", "throne room", "sensual and dominant", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "vibrant colors", "big boobs"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
