# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫臀部特写

PRESET = {
    "name": "beauty_breast_动漫臀部特写",
    "description": "动漫臀部特写",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "close-up of perfect anime buttocks", "huge round peach-shaped butt", "curvy body", "from behind"],
        "scene": ["detailed", "vibrant colors", "high quality", "sensual"],
        "style": [],
        "lighting": [],
        "quality": ["perfect curves", "anime art style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy"
}
