# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巴西美女（性感）

PRESET = {
    "name": "beauty_ethnic_巴西美女_性感",
    "description": "巴西美女（性感）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Brazilian woman", "tan skin", "curvy body", "huge round buttocks", "big natural breasts", "long dark hair", "sensual smile", "wearing tiny bikini"],
        "scene": ["Rio beach background", "golden sunset", "full body shot", "sexy pose", "summer vibe"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "exotic beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, small chest"
}
