# Auto-generated by convert_json_to_presets_v2.py
# 描述: 复古旗袍

PRESET = {
    "name": "beauty_other_复古旗袍",
    "description": "复古旗袍",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Chinese woman", "wearing elegant traditional qipao dress", "vintage style", "classic beauty", "red lips"],
        "scene": ["dark hair in updo", "standing in traditional Chinese garden", "soft golden lighting", "full body shot"],
        "style": [],
        "lighting": [],
        "quality": ["graceful pose", "cultural", "elegant"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual"
}
