# Auto-generated by convert_json_to_presets_v2.py
# 描述: 缪斯女神

PRESET = {
    "name": "beauty_classic_缪斯女神",
    "description": "缪斯女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a Greek Muse goddess of inspiration", "wearing flowing robes", "holding a lyre or scroll", "surrounded by artistic symbols", "temple of Apollo background"],
        "scene": ["soft inspiring light", "creative and elegant", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "goddess of inspiration", "divine aura"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
