# Auto-generated by convert_json_to_presets_v2.py
# 描述: 意大利美女（地中海）

PRESET = {
    "name": "beauty_ethnic_意大利美女_地中海",
    "description": "意大利美女（地中海）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Italian woman", "olive skin", "dark hair", "sensual curves", "full breasts", "round buttocks"],
        "scene": ["wearing sheer translucent lingerie", "visible body through thin fabric", "Mediterranean villa background", "warm golden lighting", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "passionate beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, explicit, pornographic, vulgar"
}
