# Auto-generated by convert_json_to_presets_v2.py
# 描述: 大臀健身

PRESET = {
    "name": "beauty_breast_大臀健身",
    "description": "大臀健身",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful athletic woman with huge round buttocks", "big booty", "fit and toned glutes", "wearing yoga pants", "plump curves"],
        "scene": ["gym background", "natural lighting", "full body shot"],
        "style": [],
        "lighting": [],
        "quality": ["confident smile", "healthy glow", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy, fat, overweight"
}
