# Auto-generated by convert_json_to_presets_v2.py
# 描述: 人体彩绘艺术

PRESET = {
    "name": "beauty_nude_人体彩绘艺术",
    "description": "人体彩绘艺术",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman with artistic body painting", "colorful patterns painted on naked body", "tribal or abstract designs", "elegant pose", "studio photography"],
        "scene": ["fine art", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["creative", "masterpiece", "vibrant colors"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
