# Auto-generated by convert_json_to_presets_v2.py
# 描述: 色气教师

PRESET = {
    "name": "beauty_anime_色气教师",
    "description": "色气教师",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful seductive teacher", "sexy schoolteacher outfit", "glasses", "tight pencil skirt", "white blouse", "holding a pointer"],
        "scene": ["classroom background", "naughty smile", "sensual pose", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, vulgar, underage"
}
