# Auto-generated by convert_json_to_presets_v2.py
# 描述: 运动健康

PRESET = {
    "name": "beauty_style_运动健康",
    "description": "运动健康",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful athletic woman", "fit and toned body", "sporty", "wearing yoga pants and sports bra", "flat tummy", "defined abs"],
        "scene": ["muscular legs", "sweaty skin", "gym background", "natural lighting"],
        "style": [],
        "lighting": [],
        "quality": ["full body shot", "confident smile", "healthy glow"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, fat, overweight, unhealthy"
}
