# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫巨乳女仆

PRESET = {
    "name": "beauty_breast_动漫巨乳女仆",
    "description": "动漫巨乳女仆",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime maid", "huge breasts", "massive cleavage spilling out of maid outfit", "wearing french maid costume", "fishnet stockings", "seductive pose"],
        "scene": ["holding a feather duster", "luxurious bedroom background", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "vibrant colors", "big boobs"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
