# Auto-generated by convert_json_to_presets_v2.py
# 描述: 透明内裤

PRESET = {
    "name": "beauty_other_透明内裤",
    "description": "透明内裤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman wearing sheer translucent panties", "see-through underwear", "visible body through thin fabric", "seductive pose", "soft bedroom lighting"],
        "scene": ["intimate atmosphere", "flawless skin", "sensual gaze"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "artistic lingerie photography"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
