# Auto-generated by convert_json_to_presets_v2.py
# 描述: 哥伦比亚美女（性感）

PRESET = {
    "name": "beauty_ethnic_哥伦比亚美女_性感",
    "description": "哥伦比亚美女（性感）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Colombian woman", "golden tan skin", "hourglass figure", "huge round buttocks", "full breasts", "dark wavy hair", "sensual gaze"],
        "scene": ["wearing tiny bikini", "Caribbean beach background", "warm lighting", "full body shot", "sexy pose"],
        "style": [],
        "lighting": [],
        "quality": ["exotic beauty", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, small chest"
}
