# Auto-generated by convert_json_to_presets_v2.py
# 描述: 蜜桃臀特写

PRESET = {
    "name": "beauty_breast_蜜桃臀特写",
    "description": "蜜桃臀特写",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman", "perfect peach-shaped buttocks", "round firm butt", "plump curves", "from behind"],
        "scene": ["artistic nude photography", "soft lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "flawless skin", "sensual and artistic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy"
}
