# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯欲风

PRESET = {
    "name": "beauty_pure_纯欲风",
    "description": "纯欲风",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful young woman", "pure and sexy", "innocent face with seductive eyes", "flawless porcelain skin", "slightly parted lips", "soft natural makeup", "disheveled hair"],
        "scene": ["wearing sheer white lace lingerie", "soft morning light", "intimate atmosphere", "cozy bedroom", "natural beauty"],
        "style": [],
        "lighting": [],
        "quality": ["alluring yet innocent", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, artificial, plastic, overdone"
}
