# Auto-generated by convert_json_to_presets_v2.py
# 描述: 禁忌游戏

PRESET = {
    "name": "beauty_sexy_禁忌游戏",
    "description": "禁忌游戏",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman", "forbidden desire", "sensual tension", "intimate gaze"],
        "scene": ["dramatic lighting", "mysterious atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "seductive expression", "artistic photography"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
