# Auto-generated by convert_json_to_presets_v2.py
# 描述: 站立后入

PRESET = {
    "name": "beauty_other_站立后入",
    "description": "站立后入",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a man and a woman having sex standing up from behind", "passionate sex", "intimate"],
        "scene": ["bedroom or bathroom setting", "soft lighting", "both bodies visible", "sensual"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury"
}
