# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳睡衣

PRESET = {
    "name": "beauty_breast_巨乳睡衣",
    "description": "巨乳睡衣",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with huge breasts", "massive cleavage", "wearing silk nightgown barely covering big boobs", "disheveled hair", "sleepy eyes", "morning sunlight"],
        "scene": ["cozy bedroom", "soft bed sheets", "natural beauty", "intimate and cozy atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "sensual"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, heavy makeup, artificial"
}
