# Auto-generated by convert_json_to_presets_v2.py
# 描述: 阿尔忒弥斯女神

PRESET = {
    "name": "beauty_classic_阿尔忒弥斯女神",
    "description": "阿尔忒弥斯女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "Artemis the Greek goddess of the hunt", "wearing ancient Greek hunting attire", "holding a bow and arrow", "moonlit forest background", "silver light"],
        "scene": ["wild and free", "majestic pose", "divine aura"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "goddess of the hunt"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
