# Auto-generated by convert_json_to_presets_v2.py
# 描述: 透视内裤（巨乳）

PRESET = {
    "name": "beauty_breast_透视内裤_巨乳",
    "description": "透视内裤（巨乳）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman with huge breasts wearing sheer translucent panties", "see-through underwear", "big boobs", "visible body through thin fabric", "seductive pose"],
        "scene": ["soft lighting", "intimate atmosphere", "flawless skin"],
        "style": [],
        "lighting": [],
        "quality": ["curvy body", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, explicit, pornographic, vulgar"
}
