# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫巨乳御姐

PRESET = {
    "name": "beauty_breast_动漫巨乳御姐",
    "description": "动漫巨乳御姐",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime woman", "huge breasts", "massive cleavage", "seductive expression", "long flowing hair", "wearing revealing outfit", "dramatic lighting"],
        "scene": ["high quality", "detailed", "vibrant colors", "anime art style"],
        "style": [],
        "lighting": [],
        "quality": ["sensual pose", "big boobs", "perfect curves"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
