# Auto-generated by convert_json_to_presets_v2.py
# 描述: 欧美辣妹

PRESET = {
    "name": "beauty_style_欧美辣妹",
    "description": "欧美辣妹",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning Western woman", "gorgeous", "sexy", "curvy body", "full lips"],
        "scene": ["bright eyes", "wearing trendy outfit", "urban background", "confident attitude"],
        "style": [],
        "lighting": [],
        "quality": ["full body shot", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, Asian features"
}
