# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫巨乳萝莉

PRESET = {
    "name": "beauty_breast_动漫巨乳萝莉",
    "description": "动漫巨乳萝莉",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a cute anime girl", "young looking", "huge breasts on petite body", "massive cleavage", "innocent yet sensual expression", "wearing revealing school uniform"],
        "scene": ["soft pastel colors", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["kawaii", "big boobs", "lolita style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, old, mature, small chest"
}
