# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳比基尼

PRESET = {
    "name": "beauty_sexy_真空巨乳比基尼",
    "description": "真空巨乳比基尼",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with huge natural breasts", "no bra", "braless", "big boobs barely contained in tiny bikini top", "massive cleavage", "perfect hourglass figure", "toned abs", "standing on a tropical beach"],
        "scene": ["ocean waves", "golden sunset", "warm lighting", "full body shot", "sexy pose"],
        "style": [],
        "lighting": [],
        "quality": ["summer vibe", "high quality", "detailed skin", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, winter, cold, explicit, pornographic"
}
