# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳和服

PRESET = {
    "name": "beauty_sexy_真空巨乳和服",
    "description": "真空巨乳和服",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Japanese woman with huge natural breasts", "no bra", "braless", "big boobs freely moving under kimono", "visible nipple outline", "massive cleavage", "wearing elegant kimono with no underwear", "cherry blossoms falling"],
        "scene": ["traditional Japanese garden", "soft pink lighting", "full body shot", "graceful pose", "serene atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, western clothes, modern, explicit, pornographic"
}
