# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤（北欧）

PRESET = {
    "name": "beauty_pure_雪白肌肤_北欧",
    "description": "雪白肌肤（北欧）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Nordic woman", "porcelain white skin", "platinum blonde hair", "pale blue eyes", "flawless complexion", "naked"],
        "scene": ["snowy Scandinavian forest background", "soft northern light", "artistic nude", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "stunning and serene", "icy beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, explicit, pornographic, vulgar"
}
