# Auto-generated by convert_json_to_presets_v2.py
# 描述: 黑白艺术裸体

PRESET = {
    "name": "beauty_nude_黑白艺术裸体",
    "description": "黑白艺术裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "black and white photography", "a beautiful woman", "artistic nude", "high contrast", "dramatic shadows", "elegant pose", "fine art"],
        "scene": ["emotional atmosphere", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "timeless beauty", "monochrome"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, color, explicit, pornographic, vulgar"
}
