# Auto-generated by convert_json_to_presets_v2.py
# 描述: 传教士体位

PRESET = {
    "name": "beauty_other_传教士体位",
    "description": "传教士体位",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a man and a woman having sex in missionary position", "man on top", "woman lying down", "intimate lovemaking", "passionate"],
        "scene": ["romantic atmosphere", "soft lighting", "bedroom setting", "both bodies visible"],
        "style": [],
        "lighting": [],
        "quality": ["sensual", "high quality", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury"
}
