# Auto-generated by convert_json_to_presets_v2.py
# 描述: 兔女郎

PRESET = {
    "name": "beauty_sexy_兔女郎",
    "description": "兔女郎",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in sexy bunny suit", "black bodysuit", "fishnet stockings", "bunny ears", "bow tie", "high heels"],
        "scene": ["playful pose", "casino or party background", "dramatic lighting", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic cosplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, vulgar"
}
