# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真丝内裤

PRESET = {
    "name": "beauty_other_真丝内裤",
    "description": "真丝内裤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in silk panties", "smooth shiny fabric", "elegant lingerie", "soft natural lighting", "sensual pose"],
        "scene": ["luxurious bedroom", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "intimate atmosphere", "sophisticated beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
