# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯白大理石卧像

PRESET = {
    "name": "beauty_classic_纯白大理石卧像",
    "description": "纯白大理石卧像",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman as a pure white marble reclining statue", "lying down", "classical sculpture", "smooth white stone", "peaceful expression", "elegant pose"],
        "scene": ["museum display", "soft lighting", "monochrome white"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "photorealistic", "masterpiece"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, color, skin tone, warm tones, beige, yellow, gray, painting, cartoon, 3d render, shiny, glossy, wet, oil, plastic, wax"
}
