# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯欲学院

PRESET = {
    "name": "beauty_pure_纯欲学院",
    "description": "纯欲学院",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful college girl", "pure and innocent with a hint of seduction", "school uniform", "white shirt slightly unbuttoned", "pleated skirt", "knee-high socks"],
        "scene": ["messy hair", "glasses", "library background", "soft window light", "shy yet alluring expression"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "natural beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, mature, old"
}
