# Auto-generated by convert_json_to_presets_v2.py
# 描述: 半透明内衣（巨乳）

PRESET = {
    "name": "beauty_sexy_半透明内衣_巨乳",
    "description": "半透明内衣（巨乳）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman with huge breasts wearing sheer translucent lingerie", "see-through lace barely containing big boobs", "visible nipple outline through thin fabric", "massive cleavage", "seductive pose"],
        "scene": ["soft romantic lighting", "intimate atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "flawless skin", "curvy body"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, explicit, pornographic, vulgar"
}
