# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳护士

PRESET = {
    "name": "beauty_breast_巨乳护士",
    "description": "巨乳护士",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy nurse with huge breasts", "massive cleavage", "tight white nurse uniform barely containing big boobs", "fishnet stockings", "stethoscope", "naughty smile"],
        "scene": ["playful eyes", "medical setting", "dramatic lighting", "sensual pose", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, gore, blood, explicit"
}
