# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳睡衣

PRESET = {
    "name": "beauty_sexy_真空巨乳睡衣",
    "description": "真空巨乳睡衣",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with huge natural breasts", "no bra", "braless", "big boobs freely swaying", "visible nipple outline", "wearing silk nightgown with nothing underneath", "massive cleavage", "disheveled hair", "sleepy eyes"],
        "scene": ["morning sunlight", "cozy bedroom", "soft bed sheets", "natural beauty", "intimate and cozy atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "sensual", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, heavy makeup, artificial, explicit, pornographic"
}
