# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳女警

PRESET = {
    "name": "beauty_breast_巨乳女警",
    "description": "巨乳女警",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy policewoman with huge breasts", "massive cleavage", "tight police uniform barely containing big boobs", "badge", "hat", "handcuffs"],
        "scene": ["confident pose", "urban background", "dramatic lighting", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, vulgar"
}
