# Auto-generated by convert_json_to_presets_v2.py
# 描述: 性感御姐

PRESET = {
    "name": "beauty_sexy_性感御姐",
    "description": "性感御姐",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning mature woman", "sexy and confident", "sultry gaze", "full red lips", "long wavy hair", "wearing elegant black dress"],
        "scene": ["hourglass figure", "perfect body", "seductive pose", "dramatic lighting", "studio photography"],
        "style": [],
        "lighting": [],
        "quality": ["high fashion", "full body shot", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, childish, innocent"
}
