# Auto-generated by convert_json_to_presets_v2.py
# 描述: 激情性爱

PRESET = {
    "name": "beauty_other_激情性爱",
    "description": "激情性爱",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a man and a woman having passionate sex", "intense lovemaking", "intimate", "bedroom setting"],
        "scene": ["dramatic lighting", "both bodies visible", "sensual"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed", "erotic atmosphere"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury"
}
