# Auto-generated by convert_json_to_presets_v2.py
# 描述: 印度美女（异域）

PRESET = {
    "name": "beauty_ethnic_印度美女_异域",
    "description": "印度美女（异域）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Indian woman", "warm brown skin", "dark eyes", "long black hair", "full curves", "natural breasts", "round buttocks", "naked"],
        "scene": ["wearing sheer translucent dupatta", "visible body through thin fabric", "Taj Mahal background", "warm golden lighting", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "exotic beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, explicit, pornographic, vulgar"
}
