# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳办公室

PRESET = {
    "name": "beauty_sexy_真空巨乳办公室",
    "description": "真空巨乳办公室",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy office lady with huge natural breasts", "no bra", "braless", "big boobs swaying under tight blouse", "visible nipple outline", "massive cleavage", "tight pencil skirt", "glasses", "stockings"],
        "scene": ["high heels", "sitting on desk", "naughty smile", "modern office background", "dramatic lighting", "sensual pose"],
        "style": [],
        "lighting": [],
        "quality": ["curvy body", "high quality", "detailed face", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, explicit, pornographic, vulgar"
}
