# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫触手

PRESET = {
    "name": "beauty_anime_动漫触手",
    "description": "动漫触手",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime woman", "tentacles wrapped around curvy body", "huge breasts", "sensual expression", "fantasy atmosphere"],
        "scene": ["dark magical setting", "dramatic lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "vibrant colors", "erotic fantasy art"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury, extreme violence"
}
