# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳和服

PRESET = {
    "name": "beauty_breast_巨乳和服",
    "description": "巨乳和服",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Japanese woman with huge breasts", "massive cleavage", "wearing elegant kimono", "big boobs prominently visible", "cherry blossoms falling"],
        "scene": ["traditional Japanese garden", "soft pink lighting", "full body shot", "graceful pose"],
        "style": [],
        "lighting": [],
        "quality": ["serene atmosphere", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, western clothes, modern"
}
