# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫百合

PRESET = {
    "name": "beauty_anime_动漫百合",
    "description": "动漫百合",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "two beautiful anime women", "intimate embrace", "kissing", "huge breasts", "sensual pose", "soft romantic lighting"],
        "scene": ["bedroom setting", "high quality", "detailed", "vibrant colors"],
        "style": [],
        "lighting": [],
        "quality": ["yuri", "girls love", "erotic and artistic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, men, heterosexual"
}
