# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫巨乳特写

PRESET = {
    "name": "beauty_breast_动漫巨乳特写",
    "description": "动漫巨乳特写",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "close-up of huge anime breasts", "massive cleavage", "big boobs", "detailed"],
        "scene": ["vibrant colors", "high quality", "seductive"],
        "style": [],
        "lighting": [],
        "quality": ["perfect curves", "anime art style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
