# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤（黑发）

PRESET = {
    "name": "beauty_pure_雪白肌肤_黑发",
    "description": "雪白肌肤（黑发）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with porcelain white skin", "snow-white complexion", "long black hair", "dramatic contrast", "flawless pale skin"],
        "scene": ["naked or sheer lingerie", "soft natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "ethereal beauty", "stunning contrast"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, explicit, pornographic, vulgar"
}
