# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯欲浴室

PRESET = {
    "name": "beauty_pure_纯欲浴室",
    "description": "纯欲浴室",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful young woman", "pure and seductive", "wet hair", "water droplets on skin", "wearing a white sheer bathrobe", "steam rising"],
        "scene": ["soft bathroom lighting", "intimate atmosphere", "natural beauty", "flawless skin", "seductive gaze"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "artistic nude"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic"
}
