# Auto-generated by convert_json_to_presets_v2.py
# 描述: 透明内裤（跪姿）

PRESET = {
    "name": "beauty_other_透明内裤_跪姿",
    "description": "透明内裤（跪姿）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman wearing sheer translucent panties", "see-through underwear", "on her knees", "visible body through thin fabric"],
        "scene": ["seductive pose", "soft dramatic lighting", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
