# Auto-generated by convert_json_to_presets_v2.py
# 描述: 岩石融合裸体

PRESET = {
    "name": "beauty_nude_岩石融合裸体",
    "description": "岩石融合裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman emerging from or melting into stone", "nude body fused with rock texture", "surreal atmosphere", "artistic fine art photography"],
        "scene": ["dramatic lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "mythical and mysterious"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
