# Auto-generated by convert_json_to_presets_v2.py
# 描述: 超现实漂浮裸体

PRESET = {
    "name": "beauty_nude_超现实漂浮裸体",
    "description": "超现实漂浮裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman floating in mid-air", "nude body", "surreal atmosphere", "dreamlike"],
        "scene": ["artistic fine art photography", "soft ethereal lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "gravity-defying elegance"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
