# Auto-generated by convert_json_to_presets_v2.py
# 描述: 厄俄斯女神

PRESET = {
    "name": "beauty_classic_厄俄斯女神",
    "description": "厄俄斯女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "Eos the Greek goddess of dawn", "rosy fingers", "golden pink sky", "flowing robes", "birds in flight"],
        "scene": ["soft morning light", "ethereal and beautiful", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "goddess of dawn", "divine aura"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
