# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫乳胶衣

PRESET = {
    "name": "beauty_breast_动漫乳胶衣",
    "description": "动漫乳胶衣",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime woman", "wearing tight shiny latex catsuit", "huge breasts prominently displayed", "glossy black material", "curves accentuated"],
        "scene": ["dramatic lighting", "futuristic or BDSM setting", "sensual pose"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed", "vibrant colors"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
