# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤（巨乳）

PRESET = {
    "name": "beauty_pure_雪白肌肤_巨乳",
    "description": "雪白肌肤（巨乳）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman with porcelain white skin", "snow-white complexion", "huge natural breasts", "flawless pale skin", "naked"],
        "scene": ["soft natural lighting", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["ethereal beauty", "pure and sensual", "curvy and pale"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, small chest, flat chest, explicit, pornographic, vulgar"
}
