# Auto-generated by convert_json_to_presets_v2.py
# 描述: 大臀女神

PRESET = {
    "name": "beauty_breast_大臀女神",
    "description": "大臀女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman with huge round buttocks", "enormous plump butt", "curvy body", "perfect hourglass figure", "from behind"],
        "scene": ["artistic nude photography", "dramatic lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "big booty", "sensual and powerful"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy, skinny"
}
