# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳运动

PRESET = {
    "name": "beauty_breast_巨乳运动",
    "description": "巨乳运动",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful athletic woman with huge breasts", "big boobs bouncing", "fit and toned body", "wearing tight sports bra barely containing massive cleavage", "yoga pants"],
        "scene": ["sweaty skin", "gym background", "natural lighting", "full body shot"],
        "style": [],
        "lighting": [],
        "quality": ["confident smile", "healthy glow", "curvy and fit"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, fat, overweight, unhealthy"
}
