# Auto-generated by convert_json_to_presets_v2.py
# 描述: 赫斯提亚女神

PRESET = {
    "name": "beauty_classic_赫斯提亚女神",
    "description": "赫斯提亚女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "Hestia the Greek goddess of hearth and home", "gentle expression", "holding a flame", "warm glowing light"],
        "scene": ["cozy domestic background", "peaceful and nurturing", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "goddess of hearth", "divine aura"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
