# Auto-generated by convert_json_to_presets_v2.py
# 描述: 束缚艺术

PRESET = {
    "name": "beauty_sexy_束缚艺术",
    "description": "束缚艺术",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with artistic restraints", "elegant bondage", "silk ropes", "sensual submission"],
        "scene": ["dramatic lighting", "artistic nude photography", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "tasteful BDSM art"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury, extreme"
}
