# Auto-generated by convert_json_to_presets_v2.py
# 描述: 捆绑艺术

PRESET = {
    "name": "beauty_sexy_捆绑艺术",
    "description": "捆绑艺术",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in artistic shibari rope bondage", "red rope wrapped around body", "elegant restraint", "sensual pose", "dramatic studio lighting"],
        "scene": ["intimate atmosphere", "fine art photography", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "flawless skin", "tasteful bondage art"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury, extreme"
}
