# Auto-generated by convert_json_to_presets_v2.py
# 描述: 私处特写（花园）

PRESET = {
    "name": "beauty_nude_私处特写_花园",
    "description": "私处特写（花园）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "artistic close-up of a woman's intimate area", "pubic region", "beautiful composition", "soft natural lighting", "delicate skin texture"],
        "scene": ["fine art nude photography", "peaceful atmosphere", "gentle shadows"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed", "tasteful"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, extreme closeup, gore, blood, injury, medical, surgery, disease, infection, shaved, completely bald"
}
