# Auto-generated by convert_json_to_presets_v2.py
# 描述: 臀部曲线（背影）

PRESET = {
    "name": "beauty_breast_臀部曲线_背影",
    "description": "臀部曲线（背影）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman", "standing from behind", "showing perfect round buttocks", "full back view", "elegant posture"],
        "scene": ["artistic nude photography", "soft lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "flawless skin", "sensual curves"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy"
}
