# Auto-generated by convert_json_to_presets_v2.py
# 描述: 赛博朋克

PRESET = {
    "name": "beauty_style_赛博朋克",
    "description": "赛博朋克",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful cyberpunk woman", "neon lights", "futuristic city", "cybernetic implants", "colorful hair", "reflective jacket"],
        "scene": ["dark atmosphere", "rain", "holographic elements", "high tech"],
        "style": [],
        "lighting": [],
        "quality": ["edgy", "full body shot", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, vintage, rustic"
}
