# Auto-generated by convert_json_to_presets_v2.py
# 描述: 尼刻女神

PRESET = {
    "name": "beauty_classic_尼刻女神",
    "description": "尼刻女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "Nike the Greek goddess of victory", "winged", "flying with laurel wreath", "golden light", "victorious pose"],
        "scene": ["dramatic clouds background", "inspiring and triumphant", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "goddess of victory", "divine aura"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
