# Auto-generated by convert_json_to_presets_v2.py
# 描述: 情侣拥抱（裸）

PRESET = {
    "name": "beauty_nude_情侣拥抱_裸",
    "description": "情侣拥抱（裸）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a man and woman embracing", "naked", "intimate hug", "passionate embrace"],
        "scene": ["nude couple", "soft romantic lighting", "bedroom setting"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed", "sensual yet artistic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
