# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巴西美女（裸体）

PRESET = {
    "name": "beauty_nude_巴西美女_裸体",
    "description": "巴西美女（裸体）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Brazilian woman", "tan skin", "curvy body", "huge round buttocks", "big natural breasts", "long dark hair", "sensual smile", "naked"],
        "scene": ["standing on a tropical beach", "ocean waves", "golden sunset", "full body shot", "artistic nude"],
        "style": [],
        "lighting": [],
        "quality": ["summer vibe", "high quality", "detailed face", "exotic beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, small chest"
}
