# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳教师

PRESET = {
    "name": "beauty_breast_巨乳教师",
    "description": "巨乳教师",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy teacher with huge breasts", "massive cleavage", "tight white blouse barely containing big boobs", "glasses", "tight pencil skirt", "stockings"],
        "scene": ["holding a pointer", "classroom background", "naughty smile", "sensual pose", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, vulgar, underage"
}
