# Auto-generated by convert_json_to_presets_v2.py
# 描述: 夜色诱惑

PRESET = {
    "name": "beauty_sexy_夜色诱惑",
    "description": "夜色诱惑",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman in the night", "city lights through window", "silhouette", "sensual pose"],
        "scene": ["mysterious atmosphere", "dramatic lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "seductive", "intimate night photography"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
