# Auto-generated by convert_json_to_presets_v2.py
# 描述: C字裤

PRESET = {
    "name": "beauty_sexy_C字裤",
    "description": "C字裤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in C-string", "minimal underwear", "invisible panty", "elegant pose"],
        "scene": ["soft lighting", "intimate atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "flawless skin", "sensual and daring"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
