# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳办公室

PRESET = {
    "name": "beauty_breast_巨乳办公室",
    "description": "巨乳办公室",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy office lady with huge breasts", "massive cleavage", "tight white blouse unbuttoned showing big boobs", "tight pencil skirt", "glasses", "stockings", "high heels"],
        "scene": ["sitting on desk", "naughty smile", "modern office background", "dramatic lighting", "sensual pose"],
        "style": [],
        "lighting": [],
        "quality": ["curvy body", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, vulgar"
}
