# Auto-generated by convert_json_to_presets_v2.py
# 描述: 瑞典美女（北欧）

PRESET = {
    "name": "beauty_ethnic_瑞典美女_北欧",
    "description": "瑞典美女（北欧）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Swedish woman", "pale skin", "blonde hair", "blue eyes", "tall and slim", "natural beauty"],
        "scene": ["naked", "standing in a Scandinavian forest", "soft northern light", "ethereal atmosphere", "artistic nude"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "stunning and serene"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
