# Auto-generated by convert_json_to_presets_v2.py
# 描述: 色气护士

PRESET = {
    "name": "beauty_anime_色气护士",
    "description": "色气护士",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful seductive nurse", "sexy nurse uniform", "white outfit", "fishnet stockings", "stethoscope", "naughty smile"],
        "scene": ["playful eyes", "medical setting", "dramatic lighting", "sensual pose", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, gore, blood, explicit"
}
