# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯白大理石维纳斯

PRESET = {
    "name": "beauty_classic_纯白大理石维纳斯",
    "description": "纯白大理石维纳斯",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman as a pure white marble Venus statue", "goddess of beauty", "classical sculpture", "flawless white stone", "elegant pose", "soft dramatic lighting"],
        "scene": ["monochrome white", "intricate details", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["photorealistic", "masterpiece", "timeless beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, color, skin tone, warm tones, beige, yellow, gray, painting, cartoon, 3d render, shiny, glossy, wet, oil, plastic, wax"
}
