# Auto-generated by convert_json_to_presets_v2.py
# 描述: 知性优雅

PRESET = {
    "name": "beauty_other_知性优雅",
    "description": "知性优雅",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "an elegant and intellectual woman", "sophisticated", "wearing professional business attire", "glasses", "confident posture"],
        "scene": ["in a modern office with city view", "soft window light", "half body shot", "intelligent expression"],
        "style": [],
        "lighting": [],
        "quality": ["refined", "classy", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, casual, sloppy"
}
