# Auto-generated by convert_json_to_presets_v2.py
# 描述: 古典油画

PRESET = {
    "name": "beauty_classic_古典油画",
    "description": "古典油画",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting style", "renaissance", "a beautiful woman in classical painting style", "soft lighting", "rich colors", "velvet dress"],
        "scene": ["pearl necklace", "elegant pose", "vintage atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["artistic masterpiece", "high quality", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern, photorealistic"
}
