# Auto-generated by convert_json_to_presets_v2.py
# 描述: 皮革束缚

PRESET = {
    "name": "beauty_sexy_皮革束缚",
    "description": "皮革束缚",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in artistic leather restraints", "elegant BDSM fashion", "black leather cuffs", "sensual pose"],
        "scene": ["dramatic studio lighting", "intimate atmosphere", "fine art photography"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "tasteful fetish art"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury"
}
