# Auto-generated by convert_json_to_presets_v2.py
# 描述: 大臀御姐

PRESET = {
    "name": "beauty_breast_大臀御姐",
    "description": "大臀御姐",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning mature woman with huge round buttocks", "enormous plump curves", "curvy hourglass body", "from behind", "elegant pose"],
        "scene": ["dramatic studio lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "big booty", "sensual and confident"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy, skinny"
}
