# Auto-generated by convert_json_to_presets_v2.py
# 描述: 光影艺术裸体

PRESET = {
    "name": "beauty_nude_光影艺术裸体",
    "description": "光影艺术裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman", "artistic nude photography", "dramatic shadows and highlights", "chiaroscuro lighting", "elegant pose", "fine art"],
        "scene": ["high contrast", "emotional atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "masterpiece", "sensual and artistic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
