# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳浴室

PRESET = {
    "name": "beauty_sexy_真空巨乳浴室",
    "description": "真空巨乳浴室",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with huge natural breasts", "no bra", "braless", "big boobs wet and glistening", "water droplets on skin", "wearing a thin wet white shirt with nothing underneath", "visible nipple outline", "massive cleavage"],
        "scene": ["steam rising", "soft bathroom lighting", "intimate atmosphere", "natural beauty", "flawless skin"],
        "style": [],
        "lighting": [],
        "quality": ["seductive gaze", "high quality", "detailed face", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, heavy makeup, explicit, pornographic"
}
