# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳女神

PRESET = {
    "name": "beauty_sexy_真空巨乳女神",
    "description": "真空巨乳女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning goddess with huge natural breasts", "no bra", "braless", "big boobs hanging naturally", "visible nipple outline through thin fabric", "massive cleavage", "perfect hourglass figure", "wearing a thin tight t-shirt with no underwear", "natural breast shape"],
        "scene": ["full rounded chest", "seductive smile", "sultry eyes", "dramatic lighting", "studio photography", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "flawless skin", "curvy body", "sexy pose"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, skinny, underweight, explicit, pornographic, vulgar"
}
