# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫兔女郎

PRESET = {
    "name": "beauty_sexy_动漫兔女郎",
    "description": "动漫兔女郎",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime bunny girl", "huge breasts", "massive cleavage", "wearing tight black bunny suit", "fishnet stockings", "bunny ears", "bow tie", "high heels"],
        "scene": ["playful pose", "casino background", "dramatic lighting", "curvy body", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "vibrant colors", "big boobs"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
