# Auto-generated by convert_json_to_presets_v2.py
# 描述: 韩系时尚

PRESET = {
    "name": "beauty_pure_韩系时尚",
    "description": "韩系时尚",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Korean woman", "trendy fashion", "stylish outfit", "flawless skin", "perfect makeup"],
        "scene": ["city street background", "soft lighting", "full body shot", "confident pose"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "K-pop style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, unfashionable, outdated"
}
