# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳浴室

PRESET = {
    "name": "beauty_breast_巨乳浴室",
    "description": "巨乳浴室",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with huge breasts", "massive cleavage", "wet hair", "water droplets on big boobs", "wearing a white sheer bathrobe", "steam rising"],
        "scene": ["soft bathroom lighting", "intimate atmosphere", "natural beauty", "flawless skin"],
        "style": [],
        "lighting": [],
        "quality": ["seductive gaze", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, heavy makeup, explicit, pornographic"
}
