# Auto-generated by convert_json_to_presets_v2.py
# 描述: 珀耳塞福涅女神

PRESET = {
    "name": "beauty_classic_珀耳塞福涅女神",
    "description": "珀耳塞福涅女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "Persephone the Greek goddess of spring and underworld", "flowers in hair", "holding pomegranate", "half spring meadow half underworld background"],
        "scene": ["mystical lighting", "dual nature beauty", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "goddess of spring", "divine aura"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
