# Auto-generated by convert_json_to_presets_v2.py
# 描述: 不良少女

PRESET = {
    "name": "beauty_pure_不良少女",
    "description": "不良少女",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful bad girl", "rebellious attitude", "leather jacket", "ripped jeans", "dark makeup"],
        "scene": ["piercing", "city alley background", "night atmosphere", "edgy and cool"],
        "style": [],
        "lighting": [],
        "quality": ["confident pose", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, sweet, innocent"
}
