# Auto-generated by convert_json_to_presets_v2.py
# 描述: 色气办公室

PRESET = {
    "name": "beauty_other_色气办公室",
    "description": "色气办公室",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful seductive office lady", "sexy business attire", "tight pencil skirt", "white blouse unbuttoned", "glasses", "stockings", "high heels"],
        "scene": ["sitting on desk", "naughty smile", "modern office background", "dramatic lighting", "sensual pose"],
        "style": [],
        "lighting": [],
        "quality": ["curvy body", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, vulgar"
}
