# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫新娘

PRESET = {
    "name": "beauty_anime_动漫新娘",
    "description": "动漫新娘",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime bride", "huge breasts", "wearing revealing wedding dress", "sheer veil", "visible body through thin fabric", "seductive pose"],
        "scene": ["romantic wedding setting", "soft lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "vibrant colors", "big boobs"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
