# Auto-generated by convert_json_to_presets_v2.py
# 描述: 猫女郎

PRESET = {
    "name": "beauty_sexy_猫女郎",
    "description": "猫女郎",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in sexy cat costume", "black bodysuit", "cat ears", "tail", "choker", "high heels"],
        "scene": ["playful pose", "mysterious atmosphere", "dramatic lighting", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic cosplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, vulgar"
}
