# Auto-generated by convert_json_to_presets_v2.py
# 描述: 韩国美女（时尚）

PRESET = {
    "name": "beauty_ethnic_韩国美女_时尚",
    "description": "韩国美女（时尚）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Korean woman", "flawless skin", "perfect body", "natural breasts", "wearing sheer translucent lingerie", "visible body through thin fabric"],
        "scene": ["no bra", "braless", "Seoul city view", "modern apartment", "soft lighting"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "elegant and trendy"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, heavy makeup, explicit, pornographic, vulgar"
}
