# Auto-generated by convert_json_to_presets_v2.py
# 描述: 古典油画裸体

PRESET = {
    "name": "beauty_nude_古典油画裸体",
    "description": "古典油画裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "classical art", "a beautiful European woman", "nude", "soft warm lighting", "rich golden tones", "elegant reclining pose"],
        "scene": ["luxurious fabrics", "classical background", "baroque style", "fine art"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed", "masterpiece painting"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
