# Auto-generated by convert_json_to_presets_v2.py
# 描述: 私处特写

PRESET = {
    "name": "beauty_nude_私处特写",
    "description": "私处特写",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "close-up shot of a beautiful woman's private area", "lower body", "intimate photography", "soft lighting", "natural skin texture"],
        "scene": ["high detail", "artistic nude", "fine art photography", "soft focus background"],
        "style": [],
        "lighting": [],
        "quality": ["intimate atmosphere", "high quality", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, extreme closeup, gore, blood, injury, medical, surgery, disease, infection"
}
