# Auto-generated by convert_json_to_presets_v2.py
# 描述: 森系少女

PRESET = {
    "name": "beauty_pure_森系少女",
    "description": "森系少女",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful forest girl", "nature lover", "wearing floral dress", "barefoot", "surrounded by trees and flowers"],
        "scene": ["dappled sunlight", "peaceful and serene", "natural beauty", "full body shot"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "ethereal"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, urban, city"
}
