# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳女仆

PRESET = {
    "name": "beauty_breast_巨乳女仆",
    "description": "巨乳女仆",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy maid with huge breasts", "massive cleavage spilling out of maid outfit", "black and white lace", "fishnet stockings", "big boobs", "curvy body"],
        "scene": ["holding a feather duster", "playful expression", "luxurious bedroom", "dramatic lighting", "sensual pose"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, vulgar"
}
