# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳女仆

PRESET = {
    "name": "beauty_sexy_真空巨乳女仆",
    "description": "真空巨乳女仆",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy maid with huge natural breasts", "no bra", "braless", "big boobs freely moving under maid outfit", "visible nipple outline", "massive cleavage", "black and white lace", "fishnet stockings", "curvy body"],
        "scene": ["holding a feather duster", "playful expression", "luxurious bedroom", "dramatic lighting", "sensual pose"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, explicit, pornographic, vulgar"
}
