# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤（内衣）

PRESET = {
    "name": "beauty_pure_雪白肌肤_内衣",
    "description": "雪白肌肤（内衣）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with porcelain white skin", "snow-white complexion", "wearing sheer translucent white lingerie", "flawless pale skin"],
        "scene": ["visible body through thin fabric", "soft romantic lighting", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "pure and sensual"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, explicit, pornographic, vulgar"
}
