# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳运动

PRESET = {
    "name": "beauty_sexy_真空巨乳运动",
    "description": "真空巨乳运动",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful athletic woman with huge natural breasts", "no bra", "braless", "big boobs bouncing freely", "wearing tight sports bra with no padding", "massive cleavage", "fit and toned body", "yoga pants"],
        "scene": ["sweaty skin", "gym background", "natural lighting", "full body shot", "confident smile"],
        "style": [],
        "lighting": [],
        "quality": ["healthy glow", "curvy and fit", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, padded, underwire, small chest, flat chest, fat, overweight, unhealthy"
}
