# Auto-generated by convert_json_to_presets_v2.py
# 描述: 英国大胸裸体

PRESET = {
    "name": "beauty_nude_英国大胸裸体",
    "description": "英国大胸裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful British woman with huge natural breasts", "big boobs", "naked", "flawless fair skin", "elegant European features"],
        "scene": ["soft natural lighting", "full body shot", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "curvy body", "sensual and artistic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat chest, small chest"
}
