# Auto-generated by convert_json_to_presets_v2.py
# 描述: 非洲美女（埃塞俄比亚）

PRESET = {
    "name": "beauty_ethnic_非洲美女_埃塞俄比亚",
    "description": "非洲美女（埃塞俄比亚）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Ethiopian woman", "dark skin", "elegant features", "slim figure", "natural breasts", "round buttocks"],
        "scene": ["naked", "African savanna background", "golden sunset", "artistic nude"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "stunning and regal"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
