# Auto-generated by convert_json_to_presets_v2.py
# 描述: 大臀牛仔裤

PRESET = {
    "name": "beauty_breast_大臀牛仔裤",
    "description": "大臀牛仔裤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with huge round buttocks", "big booty", "wearing tight jeans", "plump curves stretching the fabric", "from behind"],
        "scene": ["city street background", "natural lighting", "full body shot", "sexy pose"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed", "denim look"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy"
}
