# Auto-generated by convert_json_to_presets_v2.py
# 描述: 半透明薄纱睡衣

PRESET = {
    "name": "beauty_sexy_半透明薄纱睡衣",
    "description": "半透明薄纱睡衣",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in sheer translucent nightgown", "see-through chiffon fabric", "visible body silhouette", "soft morning light"],
        "scene": ["cozy bedroom", "natural beauty", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "sensual and elegant"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
