# Auto-generated by convert_json_to_presets_v2.py
# 描述: 古典站立裸体

PRESET = {
    "name": "beauty_nude_古典站立裸体",
    "description": "古典站立裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "classical art", "a beautiful European woman", "standing nude", "elegant contrapposto pose", "soft warm lighting", "classical background"],
        "scene": ["fine art", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "timeless beauty", "venus pudica style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
