# Auto-generated by convert_json_to_presets_v2.py
# 描述: 哥伦比亚美女（裸体）

PRESET = {
    "name": "beauty_nude_哥伦比亚美女_裸体",
    "description": "哥伦比亚美女（裸体）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Colombian woman", "golden tan skin", "hourglass figure", "huge round buttocks", "full breasts", "dark wavy hair", "sensual gaze"],
        "scene": ["naked", "Caribbean beach background", "warm lighting", "full body shot", "artistic nude"],
        "style": [],
        "lighting": [],
        "quality": ["exotic beauty", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, small chest"
}
