# Auto-generated by convert_json_to_presets_v2.py
# 描述: 布纹艺术裸体

PRESET = {
    "name": "beauty_nude_布纹艺术裸体",
    "description": "布纹艺术裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman wrapped in flowing fabric", "nude body partially covered by silk", "elegant drapery", "classical sculpture style"],
        "scene": ["soft lighting", "fine art photography", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "timeless beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
