# Auto-generated by convert_json_to_presets_v2.py
# 描述: 校园初恋

PRESET = {
    "name": "beauty_pure_校园初恋",
    "description": "校园初恋",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful girl next door", "campus beauty", "first love feeling", "wearing casual school uniform", "backpack"],
        "scene": ["shy smile", "cherry blossom background", "soft sunlight", "youthful and fresh"],
        "style": [],
        "lighting": [],
        "quality": ["full body shot", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, mature, heavy makeup"
}
