# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤（东欧）

PRESET = {
    "name": "beauty_pure_雪白肌肤_东欧",
    "description": "雪白肌肤（东欧）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Eastern European woman", "porcelain white skin", "pale complexion", "dark hair", "striking contrast"],
        "scene": ["flawless skin", "naked", "soft natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "mysterious and elegant", "timeless beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, explicit, pornographic, vulgar"
}
