# Auto-generated by convert_json_to_presets_v2.py
# 描述: 私处特写（浴光）

PRESET = {
    "name": "beauty_nude_私处特写_浴光",
    "description": "私处特写（浴光）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "intimate photography of woman's lower body", "soft window light", "warm golden tones", "artistic nude", "delicate skin"],
        "scene": ["feminine beauty", "elegant pose", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "tasteful", "peaceful atmosphere"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, extreme closeup, gore, blood, injury, medical, surgery, disease, infection"
}
