# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫巨乳护士

PRESET = {
    "name": "beauty_breast_动漫巨乳护士",
    "description": "动漫巨乳护士",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime nurse", "huge breasts", "massive cleavage barely contained in tight nurse uniform", "short white dress", "fishnet stockings", "naughty smile"],
        "scene": ["medical setting", "dramatic lighting", "sensual pose", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "vibrant colors", "big boobs"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest, gore, blood"
}
