# Auto-generated by convert_json_to_presets_v2.py
# 描述: 晨光私密

PRESET = {
    "name": "beauty_pure_晨光私密",
    "description": "晨光私密",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in bed", "morning sunlight", "messy hair", "sleepy eyes", "wearing only a sheet"],
        "scene": ["intimate morning atmosphere", "soft warm lighting", "natural beauty"],
        "style": [],
        "lighting": [],
        "quality": ["sensual and cozy", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
