# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯白希腊女神雕像

PRESET = {
    "name": "beauty_classic_纯白希腊女神雕像",
    "description": "纯白希腊女神雕像",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman as a pure white Greek goddess statue", "classical Greek sculpture", "flawless marble", "flowing robes", "elegant pose", "ancient temple background"],
        "scene": ["dramatic lighting", "monochrome white", "intricate details"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "photorealistic", "masterpiece"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, color, skin tone, warm tones, beige, yellow, gray, painting, cartoon, 3d render, shiny, glossy, wet, oil, plastic, wax"
}
