# Auto-generated by convert_json_to_presets_v2.py
# 描述: 赫拉女神

PRESET = {
    "name": "beauty_classic_赫拉女神",
    "description": "赫拉女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "Hera the Greek goddess of marriage", "wearing a majestic crown", "royal robes", "holding a scepter", "peacock background"],
        "scene": ["dramatic lighting", "regal and powerful", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "goddess of marriage", "divine aura"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
