# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫天使

PRESET = {
    "name": "beauty_anime_动漫天使",
    "description": "动漫天使",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime angel", "huge breasts", "white wings", "flowing white robes", "heavenly glow", "soft golden lighting"],
        "scene": ["cloudy sky background", "divine beauty", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["vibrant colors", "big boobs", "ethereal and sensual"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
