# Auto-generated by convert_json_to_presets_v2.py
# 描述: 蜜桃臀（站姿）

PRESET = {
    "name": "beauty_breast_蜜桃臀_站姿",
    "description": "蜜桃臀（站姿）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman standing", "perfect round buttocks", "from behind view", "curvy body", "elegant posture"],
        "scene": ["artistic nude photography", "soft natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "flawless skin", "sensual curves"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy"
}
