# Auto-generated by convert_json_to_presets_v2.py
# 描述: 半透明蕾丝内衣

PRESET = {
    "name": "beauty_sexy_半透明蕾丝内衣",
    "description": "半透明蕾丝内衣",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman in sheer lace lingerie", "translucent fabric", "see-through lace bra and panties", "visible curves through thin material", "elegant seductive pose"],
        "scene": ["romantic lighting", "luxurious bedroom", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "flawless skin", "intimate atmosphere"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
