# Auto-generated by convert_json_to_presets_v2.py
# 描述: 私处特写（自然）

PRESET = {
    "name": "beauty_nude_私处特写_自然",
    "description": "私处特写（自然）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "beautiful woman's private parts", "natural pubic hair", "intimate photography", "soft warm lighting", "artistic nude"],
        "scene": ["feminine area", "natural beauty", "peaceful atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "tasteful", "elegant composition"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, extreme closeup, shaved, completely bald, gore, blood, injury, medical, surgery, disease, infection"
}
