# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳居家

PRESET = {
    "name": "beauty_sexy_真空巨乳居家",
    "description": "真空巨乳居家",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with huge natural breasts", "no bra", "braless", "big boobs freely moving under loose t-shirt", "visible nipple outline", "massive cleavage", "wearing oversized t-shirt with nothing underneath", "cozy home atmosphere"],
        "scene": ["morning sunlight", "relaxed and natural", "bed hair", "natural beauty", "warm lighting"],
        "style": [],
        "lighting": [],
        "quality": ["intimate atmosphere", "half body shot", "high quality", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, formal, business, explicit, pornographic"
}
