# Auto-generated by convert_json_to_presets_v2.py
# 描述: 蜜桃臀（丁字裤）

PRESET = {
    "name": "beauty_sexy_蜜桃臀_丁字裤",
    "description": "蜜桃臀（丁字裤）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in thong", "perfect round buttocks", "plump curves", "from behind", "elegant pose"],
        "scene": ["soft natural lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "sensual and artistic", "swimsuit photography"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy"
}
