# Auto-generated by convert_json_to_presets_v2.py
# 描述: 法国美女（优雅）

PRESET = {
    "name": "beauty_ethnic_法国美女_优雅",
    "description": "法国美女（优雅）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful French woman", "elegant", "sophisticated", "pale skin", "slim figure", "natural breasts", "wearing sheer translucent lingerie", "no bra"],
        "scene": ["braless", "visible body through thin fabric", "Parisian bedroom", "soft morning light", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "timeless elegance"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, heavy makeup, explicit, pornographic, vulgar"
}
