# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雅典娜女神

PRESET = {
    "name": "beauty_classic_雅典娜女神",
    "description": "雅典娜女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "Athena the Greek goddess of wisdom", "wearing ancient Greek armor and helmet", "holding a spear and shield", "majestic pose", "temple of Athena background"],
        "scene": ["dramatic golden lighting", "divine aura", "powerful and wise"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "goddess of wisdom"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
