# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯欲睡衣

PRESET = {
    "name": "beauty_pure_纯欲睡衣",
    "description": "纯欲睡衣",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful young woman", "pure and alluring", "wearing silk nightgown", "disheveled hair", "sleepy eyes", "morning sunlight"],
        "scene": ["cozy bedroom", "soft bed sheets", "natural beauty", "intimate and cozy atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "sensual yet innocent"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, artificial"
}
