# Auto-generated by convert_json_to_presets_v2.py
# 描述: 比基尼海滩

PRESET = {
    "name": "beauty_sexy_比基尼海滩",
    "description": "比基尼海滩",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in bikini", "perfect body", "toned abs", "standing on a tropical beach", "ocean waves"],
        "scene": ["golden sunset", "warm lighting", "full body shot", "sexy pose"],
        "style": [],
        "lighting": [],
        "quality": ["summer vibe", "high quality", "detailed skin"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, winter, cold"
}
