# Auto-generated by convert_json_to_presets_v2.py
# 描述: 蜜桃臀（弯腰）

PRESET = {
    "name": "beauty_breast_蜜桃臀_弯腰",
    "description": "蜜桃臀（弯腰）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman bent over", "perfect round buttocks prominently displayed", "from behind", "curvy body"],
        "scene": ["artistic nude photography", "soft dramatic lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "flawless skin", "sensual and alluring"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy"
}
