# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳护士

PRESET = {
    "name": "beauty_sexy_真空巨乳护士",
    "description": "真空巨乳护士",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy nurse with huge natural breasts", "no bra", "braless", "big boobs barely contained in tight nurse uniform", "visible nipple outline", "massive cleavage", "fishnet stockings", "stethoscope", "naughty smile"],
        "scene": ["playful eyes", "medical setting", "dramatic lighting", "sensual pose", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, gore, blood, explicit, pornographic"
}
