# Auto-generated by convert_json_to_presets_v2.py
# 描述: 半透明情趣内衣

PRESET = {
    "name": "beauty_sexy_半透明情趣内衣",
    "description": "半透明情趣内衣",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in sexy sheer lingerie", "translucent mesh fabric", "see-through bodysuit", "visible body outline", "seductive expression"],
        "scene": ["dramatic lighting", "intimate bedroom setting", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic yet tasteful"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
