# Auto-generated by convert_json_to_presets_v2.py
# 描述: 清纯甜美

PRESET = {
    "name": "beauty_pure_清纯甜美",
    "description": "清纯甜美",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful young Asian woman", "sweet smile", "pure and innocent", "flawless skin", "long black hair", "wearing white sundress"],
        "scene": ["natural makeup", "soft natural lighting", "standing in a flower field", "gentle breeze"],
        "style": [],
        "lighting": [],
        "quality": ["full body shot", "detailed face", "high resolution"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, makeup heavy, seductive, mature"
}
