# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳空姐

PRESET = {
    "name": "beauty_breast_巨乳空姐",
    "description": "巨乳空姐",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy flight attendant with huge breasts", "massive cleavage", "tight airline uniform barely containing big boobs", "hat", "scarf"],
        "scene": ["professional yet seductive pose", "airplane cabin background", "dramatic lighting", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, vulgar"
}
