# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳御姐

PRESET = {
    "name": "beauty_sexy_真空巨乳御姐",
    "description": "真空巨乳御姐",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning mature woman with huge natural breasts", "no bra", "braless", "big boobs hanging freely", "visible nipple outline", "massive cleavage", "wearing an elegant thin silk blouse with no bra", "perfect hourglass figure", "full red lips"],
        "scene": ["long wavy hair", "seductive pose", "dramatic lighting", "studio photography", "high fashion", "full body shot"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "confident", "sexy", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, childish, innocent, explicit, pornographic"
}
