# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳女佣

PRESET = {
    "name": "beauty_breast_巨乳女佣",
    "description": "巨乳女佣",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy housemaid with huge breasts", "massive cleavage", "tight maid uniform", "big boobs", "holding cleaning supplies", "playful expression"],
        "scene": ["luxurious mansion background", "dramatic lighting", "sensual pose", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, vulgar"
}
