# Auto-generated by convert_json_to_presets_v2.py
# 描述: 诱人曲线

PRESET = {
    "name": "beauty_other_诱人曲线",
    "description": "诱人曲线",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman", "perfect hourglass figure", "sensual curves", "elegant pose"],
        "scene": ["dramatic lighting", "artistic nude photography", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "flawless skin", "tempting silhouette"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
