# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤（宫廷）

PRESET = {
    "name": "beauty_pure_雪白肌肤_宫廷",
    "description": "雪白肌肤（宫廷）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with porcelain white skin", "snow-white complexion", "wearing elegant white gown or corset", "flawless pale skin", "dramatic contrast"],
        "scene": ["luxurious palace background", "soft golden lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "regal and pure", "timeless beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, explicit, pornographic, vulgar"
}
