# Auto-generated by convert_json_to_presets_v2.py
# 描述: 复古港风

PRESET = {
    "name": "beauty_pure_复古港风",
    "description": "复古港风",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in classic Hong Kong retro style", "90s fashion", "vintage makeup", "red lips", "oversized jacket"],
        "scene": ["high-waisted jeans", "city night background", "neon signs"],
        "style": [],
        "lighting": [],
        "quality": ["nostalgic atmosphere", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern fashion"
}
