# Auto-generated by convert_json_to_presets_v2.py
# 描述: 私处特写（森林）

PRESET = {
    "name": "beauty_nude_私处特写_森林",
    "description": "私处特写（森林）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "artistic nude in nature", "woman's intimate area", "forest background", "dappled sunlight", "natural beauty"],
        "scene": ["feminine area", "tasteful", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "serene atmosphere", "connection with nature"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, extreme closeup, gore, blood, injury, medical, surgery, disease, infection"
}
