# Auto-generated by convert_json_to_presets_v2.py
# 描述: 半透明内衣（浴室）

PRESET = {
    "name": "beauty_sexy_半透明内衣_浴室",
    "description": "半透明内衣（浴室）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in sheer translucent lingerie", "wet see-through fabric clinging to body", "visible skin through thin material", "steam rising", "soft bathroom lighting"],
        "scene": ["intimate atmosphere", "water droplets on skin", "seductive gaze"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "sensual"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
