# Auto-generated by convert_json_to_presets_v2.py
# 描述: 油光诱惑

PRESET = {
    "name": "beauty_sexy_油光诱惑",
    "description": "油光诱惑",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman with oiled skin", "glistening body", "sensual shine", "perfect curves", "dramatic lighting"],
        "scene": ["intimate atmosphere", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "seductive pose", "artistic nude photography"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
