# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真丝内裤（巨乳）

PRESET = {
    "name": "beauty_breast_真丝内裤_巨乳",
    "description": "真丝内裤（巨乳）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman with huge breasts in silk panties", "smooth shiny fabric", "big boobs", "elegant lingerie", "soft lighting"],
        "scene": ["sensual pose", "luxurious bedroom", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "curvy body", "sophisticated beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, pornographic, vulgar"
}
