# Auto-generated by convert_json_to_presets_v2.py
# 描述: 湿身诱惑

PRESET = {
    "name": "beauty_sexy_湿身诱惑",
    "description": "湿身诱惑",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with wet body", "water droplets on skin", "wet hair", "wearing thin white shirt soaked and clinging to body"],
        "scene": ["sensual wet look", "soft lighting", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "seductive"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
