# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯白大理石雕像

PRESET = {
    "name": "beauty_classic_纯白大理石雕像",
    "description": "纯白大理石雕像",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman turned into a flawless pure white marble statue", "classical sculpture", "pure white stone", "smooth marble texture", "elegant pose", "museum display"],
        "scene": ["dramatic lighting", "no color", "monochrome white", "intricate carving details"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "photorealistic", "masterpiece"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, color, skin tone, warm tones, beige, yellow, gray, painting, cartoon, 3d render, shiny, glossy, wet, oil, plastic, wax"
}
