# Auto-generated by convert_json_to_presets_v2.py
# 描述: 蜜桃臀（坐姿）

PRESET = {
    "name": "beauty_breast_蜜桃臀_坐姿",
    "description": "蜜桃臀（坐姿）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman sitting", "showing perfect buttocks curve", "side profile", "full curves"],
        "scene": ["artistic nude photography", "soft natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "flawless skin", "elegant and sensual"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt"
}
