# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳御姐

PRESET = {
    "name": "beauty_breast_巨乳御姐",
    "description": "巨乳御姐",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning mature woman with huge breasts", "massive cleavage", "enormous boobs", "perfect hourglass figure", "wearing elegant black dress showing big chest", "full red lips", "long wavy hair"],
        "scene": ["seductive pose", "dramatic lighting", "studio photography", "high fashion", "full body shot"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "confident", "sexy"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, childish, innocent"
}
