# Auto-generated by convert_json_to_presets_v2.py
# 描述: 大臀比基尼

PRESET = {
    "name": "beauty_sexy_大臀比基尼",
    "description": "大臀比基尼",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with huge round buttocks", "big booty", "wearing tiny bikini bottom", "plump curves", "standing on a beach"],
        "scene": ["ocean background", "golden sunset", "full body shot", "sexy pose"],
        "style": [],
        "lighting": [],
        "quality": ["summer vibe", "high quality", "detailed skin"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy, winter, cold"
}
