# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳旗袍

PRESET = {
    "name": "beauty_breast_巨乳旗袍",
    "description": "巨乳旗袍",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Chinese woman with huge breasts", "massive cleavage", "wearing elegant traditional qipao dress", "big boobs stretching the fabric", "vintage style", "classic beauty", "red lips"],
        "scene": ["dark hair in updo", "standing in traditional Chinese garden", "soft golden lighting", "full body shot", "graceful pose"],
        "style": [],
        "lighting": [],
        "quality": ["cultural", "elegant", "sexy"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, modern clothes, casual"
}
