# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤（月光）

PRESET = {
    "name": "beauty_pure_雪白肌肤_月光",
    "description": "雪白肌肤（月光）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with porcelain white skin", "snow-white complexion", "glowing in moonlight", "flawless pale skin", "naked"],
        "scene": ["night setting", "soft silver light", "ethereal atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "mystical and pure", "moon goddess"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, explicit, pornographic, vulgar"
}
