# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤（红发）

PRESET = {
    "name": "beauty_pure_雪白肌肤_红发",
    "description": "雪白肌肤（红发）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with porcelain white skin", "snow-white complexion", "long red hair", "striking contrast", "flawless pale skin"],
        "scene": ["freckles", "naked or sheer fabric", "soft natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "ethereal beauty", "unique and stunning"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, explicit, pornographic, vulgar"
}
