# Auto-generated by convert_json_to_presets_v2.py
# 描述: 樱花和服

PRESET = {
    "name": "beauty_other_樱花和服",
    "description": "樱花和服",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Japanese woman", "wearing elegant kimono", "cherry blossoms falling", "traditional Japanese garden"],
        "scene": ["soft pink lighting", "full body shot", "graceful pose"],
        "style": [],
        "lighting": [],
        "quality": ["serene atmosphere", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, western clothes, modern"
}
