# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫精灵

PRESET = {
    "name": "beauty_anime_动漫精灵",
    "description": "动漫精灵",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime elf", "huge breasts", "long pointed ears", "flowing silver hair", "wearing sheer translucent robes", "visible body through thin fabric"],
        "scene": ["magical forest background", "soft ethereal lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["vibrant colors", "big boobs", "fantasy beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
