# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫巫女

PRESET = {
    "name": "beauty_anime_动漫巫女",
    "description": "动漫巫女",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime shrine maiden", "huge breasts", "wearing revealing miko outfit", "white and red", "seductive pose", "traditional Japanese shrine background"],
        "scene": ["soft lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["vibrant colors", "big boobs", "spiritual yet sensual"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
