# Auto-generated by convert_json_to_presets_v2.py
# 描述: 俄罗斯美女（东欧）

PRESET = {
    "name": "beauty_ethnic_俄罗斯美女_东欧",
    "description": "俄罗斯美女（东欧）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Russian woman", "pale skin", "blonde hair", "piercing blue eyes", "tall and elegant", "big natural breasts"],
        "scene": ["round buttocks", "naked", "snowy forest background", "soft northern light", "artistic nude"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "stunning and mysterious"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
