# Auto-generated by convert_json_to_presets_v2.py
# 描述: 丁字裤（巨乳）

PRESET = {
    "name": "beauty_sexy_丁字裤_巨乳",
    "description": "丁字裤（巨乳）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman with huge breasts in thong", "tiny underwear", "big boobs", "perfect round buttocks", "elegant pose"],
        "scene": ["soft lighting", "luxurious bedroom", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "curvy body", "sensual and seductive"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, pornographic, vulgar"
}
