# Auto-generated by convert_json_to_presets_v2.py
# 描述: 西班牙大胸裸体

PRESET = {
    "name": "beauty_nude_西班牙大胸裸体",
    "description": "西班牙大胸裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Spanish woman with huge natural breasts", "big boobs", "naked", "flawless tan skin", "elegant Mediterranean features"],
        "scene": ["soft warm lighting", "full body shot", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "curvy body", "sensual and artistic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat chest, small chest"
}
