# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳兔女郎

PRESET = {
    "name": "beauty_sexy_巨乳兔女郎",
    "description": "巨乳兔女郎",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy bunny girl with huge breasts", "massive cleavage", "tight black bodysuit barely containing big boobs", "fishnet stockings", "bunny ears", "bow tie"],
        "scene": ["high heels", "playful pose", "casino background", "dramatic lighting", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic cosplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, explicit, vulgar"
}
