# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳旗袍

PRESET = {
    "name": "beauty_sexy_真空巨乳旗袍",
    "description": "真空巨乳旗袍",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Chinese woman with huge natural breasts", "no bra", "braless", "big boobs stretching the silk fabric", "visible nipple outline", "massive cleavage", "wearing elegant traditional qipao dress with no underwear", "vintage style", "classic beauty"],
        "scene": ["red lips", "dark hair in updo", "standing in traditional Chinese garden", "soft golden lighting", "full body shot", "graceful pose"],
        "style": [],
        "lighting": [],
        "quality": ["cultural", "elegant", "sexy", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, modern clothes, casual, explicit, pornographic"
}
