# Auto-generated by convert_json_to_presets_v2.py
# 描述: 几何光影裸体

PRESET = {
    "name": "beauty_nude_几何光影裸体",
    "description": "几何光影裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman with geometric light patterns on naked body", "shadow play", "artistic nude photography", "modern abstract style"],
        "scene": ["high contrast", "fine art", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "creative lighting design"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
