# Auto-generated by convert_json_to_presets_v2.py
# 描述: 真空巨乳教师

PRESET = {
    "name": "beauty_sexy_真空巨乳教师",
    "description": "真空巨乳教师",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful sexy teacher with huge natural breasts", "no bra", "braless", "big boobs freely moving under tight blouse", "visible nipple outline", "massive cleavage", "glasses", "tight pencil skirt", "stockings"],
        "scene": ["holding a pointer", "classroom background", "naughty smile", "sensual pose", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay", "natural bounce"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, padded, small chest, flat chest, explicit, pornographic, vulgar, underage"
}
