# Auto-generated by convert_json_to_presets_v2.py
# 描述: 后入体位

PRESET = {
    "name": "beauty_other_后入体位",
    "description": "后入体位",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a man and a woman having sex in doggy style position", "from behind", "passionate sex", "intimate"],
        "scene": ["bedroom setting", "soft lighting", "both bodies visible"],
        "style": [],
        "lighting": [],
        "quality": ["sensual", "high quality", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury"
}
