# Auto-generated by convert_json_to_presets_v2.py
# 描述: 阿佛洛狄忒女神

PRESET = {
    "name": "beauty_classic_阿佛洛狄忒女神",
    "description": "阿佛洛狄忒女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "Aphrodite the Greek goddess of love and beauty", "emerging from sea foam", "flowing golden hair", "flawless body", "nude or draped in sheer fabric"],
        "scene": ["seashells", "soft romantic lighting", "divine beauty", "enchanting smile"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "goddess of love"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
