# Auto-generated by convert_json_to_presets_v2.py
# 描述: 丁字裤

PRESET = {
    "name": "beauty_sexy_丁字裤",
    "description": "丁字裤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in thong", "tiny underwear", "perfect round buttocks", "elegant pose", "soft lighting"],
        "scene": ["luxurious bedroom", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "intimate atmosphere", "sensual and seductive"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
