# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫巨乳教师

PRESET = {
    "name": "beauty_breast_动漫巨乳教师",
    "description": "动漫巨乳教师",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime teacher", "huge breasts", "massive cleavage in tight blouse", "glasses", "tight pencil skirt", "stockings", "holding a pointer"],
        "scene": ["classroom background", "naughty smile", "sensual pose", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "vibrant colors", "big boobs"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest, underage"
}
