# Auto-generated by convert_json_to_presets_v2.py
# 描述: 开裆内裤

PRESET = {
    "name": "beauty_sexy_开裆内裤",
    "description": "开裆内裤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in crotchless panties", "open-crotch underwear", "seductive lingerie", "elegant pose"],
        "scene": ["soft dramatic lighting", "intimate atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "flawless skin", "sensual and provocative"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
