# Auto-generated by convert_json_to_presets_v2.py
# 描述: 轻纱艺术裸体

PRESET = {
    "name": "beauty_nude_轻纱艺术裸体",
    "description": "轻纱艺术裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in translucent veil", "nude body visible through thin fabric", "soft romantic lighting", "elegant pose"],
        "scene": ["artistic nude photography", "dreamy atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "masterpiece", "sensual and ethereal"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
