# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巨乳女神

PRESET = {
    "name": "beauty_breast_巨乳女神",
    "description": "巨乳女神",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning goddess with huge breasts", "massive cleavage", "enormous natural breasts", "perfect hourglass figure", "full rounded chest", "wearing a tight low-cut dress", "seductive smile", "sultry eyes"],
        "scene": ["dramatic lighting", "studio photography", "high quality", "detailed face", "flawless skin"],
        "style": [],
        "lighting": [],
        "quality": ["big boobs", "curvy body", "sexy pose"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, small chest, flat chest, skinny, underweight"
}
