# Auto-generated by convert_json_to_presets_v2.py
# 描述: 色气满满

PRESET = {
    "name": "beauty_sexy_色气满满",
    "description": "色气满满",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunningly beautiful woman", "extremely seductive", "sultry gaze", "full red lips", "flawless hourglass figure", "wearing sexy black lace lingerie", "fishnet stockings", "high heels"],
        "scene": ["dramatic lighting", "bedroom setting", "intimate atmosphere", "sensual pose", "perfect body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic yet artistic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
