# Auto-generated by convert_json_to_presets_v2.py
# 描述: 私处特写（唯美）

PRESET = {
    "name": "beauty_nude_私处特写_唯美",
    "description": "私处特写（唯美）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "artistic intimate photography", "woman's lower body", "soft focus", "beautiful lighting", "feminine curves"],
        "scene": ["tasteful nude", "delicate skin", "intimate atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "fine art", "elegant"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, extreme closeup, gore, blood, injury, medical, surgery, disease, infection, shaved"
}
