# Auto-generated by convert_json_to_presets_v2.py
# 描述: 仙女风

PRESET = {
    "name": "beauty_pure_仙女风",
    "description": "仙女风",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "an ethereal goddess", "beautiful angelic woman", "flowing white dress", "long silky hair", "glowing skin", "surrounded by soft mist and flowers"],
        "scene": ["magical atmosphere", "dreamy lighting", "fantasy", "ethereal beauty"],
        "style": [],
        "lighting": [],
        "quality": ["full body shot", "perfect face", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, dark, scary"
}
