# Auto-generated by convert_json_to_presets_v2.py
# 描述: 臀部曲线（侧身）

PRESET = {
    "name": "beauty_breast_臀部曲线_侧身",
    "description": "臀部曲线（侧身）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman", "side profile showing perfect buttocks curve", "S-curve body", "hourglass silhouette"],
        "scene": ["artistic nude photography", "soft natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "flawless skin", "elegant and sensual"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt"
}
