# Auto-generated by convert_json_to_presets_v2.py
# 描述: 极简艺术裸体

PRESET = {
    "name": "beauty_nude_极简艺术裸体",
    "description": "极简艺术裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "minimalism art style", "a beautiful woman", "artistic nude photography", "clean background", "simple composition"],
        "scene": ["elegant pose", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["fine art", "modern minimalist"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
