# Auto-generated by convert_json_to_presets_v2.py
# 描述: 日本美女（和服）

PRESET = {
    "name": "beauty_ethnic_日本美女_和服",
    "description": "日本美女（和服）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Japanese woman", "flawless skin", "dark hair", "elegant", "wearing kimono with nothing underneath", "visible body silhouette"],
        "scene": ["cherry blossoms background", "traditional Japanese garden", "soft lighting", "intimate atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "graceful beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bra, underwear, heavy makeup, explicit, pornographic, vulgar"
}
