# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫恶魔娘

PRESET = {
    "name": "beauty_anime_动漫恶魔娘",
    "description": "动漫恶魔娘",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime demon girl", "huge breasts", "horns", "wings", "tail", "revealing dark outfit", "seductive expression"],
        "scene": ["hellfire background", "dramatic lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["vibrant colors", "big boobs", "dark fantasy beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
