# Auto-generated by convert_json_to_presets_v2.py
# 描述: 蜜桃臀（趴姿）

PRESET = {
    "name": "beauty_breast_蜜桃臀_趴姿",
    "description": "蜜桃臀（趴姿）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman lying on her stomach", "perfect round buttocks prominently displayed", "from behind", "relaxed pose"],
        "scene": ["artistic nude photography", "soft morning light", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "flawless skin", "sensual and peaceful"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, saggy"
}
