# Auto-generated by convert_json_to_presets_v2.py
# 描述: 古希腊女神像

PRESET = {
    "name": "beauty_classic_古希腊女神像",
    "description": "古希腊女神像",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful ancient Greek goddess", "classical Greek sculpture", "flowing white robes", "golden laurel wreath", "standing in a temple", "soft marble columns"],
        "scene": ["dramatic golden lighting", "divine aura", "majestic pose", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "flawless skin", "ethereal beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes, casual, cartoon, anime, explicit, pornographic"
}
