# Auto-generated by convert_json_to_presets_v2.py
# 描述: 高腰内裤

PRESET = {
    "name": "beauty_other_高腰内裤",
    "description": "高腰内裤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in high-waisted panties", "retro style underwear", "elegant vintage lingerie"],
        "scene": ["soft lighting", "intimate atmosphere", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "feminine beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
