# Auto-generated by convert_json_to_presets_v2.py
# 描述: 睡衣居家

PRESET = {
    "name": "beauty_pure_睡衣居家",
    "description": "睡衣居家",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in silk pajamas", "cozy home atmosphere", "morning sunlight", "sitting on a comfortable bed", "relaxed and natural"],
        "scene": ["bed hair", "natural beauty", "warm lighting"],
        "style": [],
        "lighting": [],
        "quality": ["intimate atmosphere", "half body shot", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, formal, business"
}
