# Auto-generated by convert_json_to_presets_v2.py
# 描述: 浮世绘裸体

PRESET = {
    "name": "beauty_nude_浮世绘裸体",
    "description": "浮世绘裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "ukiyo-e style", "japanese woodblock print", "a beautiful Japanese woman", "nude", "elegant pose"],
        "scene": ["traditional style", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["artistic", "classic Japanese art"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
