# Auto-generated by convert_json_to_presets_v2.py
# 描述: 诱惑凝视

PRESET = {
    "name": "beauty_sexy_诱惑凝视",
    "description": "诱惑凝视",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning woman with seductive eyes", "intense gaze", "bedroom eyes", "sensual expression", "soft lighting"],
        "scene": ["intimate atmosphere", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "tempting smile", "alluring pose"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
