# Auto-generated by convert_json_to_presets_v2.py
# 描述: 色气女仆

PRESET = {
    "name": "beauty_anime_色气女仆",
    "description": "色气女仆",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful seductive maid", "sexy French maid outfit", "black and white lace", "fishnet stockings", "apron", "holding a feather duster"],
        "scene": ["playful expression", "luxurious bedroom", "dramatic lighting", "sensual pose", "curvy body"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "erotic roleplay"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, vulgar"
}
