# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫捆绑艺术

PRESET = {
    "name": "beauty_sexy_动漫捆绑艺术",
    "description": "动漫捆绑艺术",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime woman", "artistic shibari rope bondage", "red ropes wrapped around huge breasts and curvy body", "sensual submission"],
        "scene": ["dramatic lighting", "intimate atmosphere", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["vibrant colors", "tasteful bondage art"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, gore, blood, injury, extreme"
}
