# Auto-generated by convert_json_to_presets_v2.py
# 描述: 蕾丝内裤

PRESET = {
    "name": "beauty_sexy_蕾丝内裤",
    "description": "蕾丝内裤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman in lace panties", "delicate floral lace", "elegant intimate wear", "soft romantic lighting", "sensual pose"],
        "scene": ["luxurious bedroom", "high quality", "detailed face"],
        "style": [],
        "lighting": [],
        "quality": ["flawless skin", "intimate atmosphere", "feminine beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
