# Auto-generated by convert_json_to_presets_v2.py
# 描述: 动漫猫女郎

PRESET = {
    "name": "beauty_sexy_动漫猫女郎",
    "description": "动漫猫女郎",
    "layers": {
        "subject": ["masterpiece", "best quality", "anime style", "a beautiful anime cat girl", "huge breasts", "massive cleavage", "wearing tight black cat suit", "cat ears", "tail", "choker", "high heels"],
        "scene": ["playful pose", "mysterious atmosphere", "dramatic lighting", "curvy body", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "vibrant colors", "big boobs"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, small chest, flat chest"
}
