# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪白肌肤

PRESET = {
    "name": "beauty_pure_雪白肌肤",
    "description": "雪白肌肤",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful woman with porcelain white skin", "snow-white complexion", "flawless pale skin", "glowing ivory skin"],
        "scene": ["stunning beauty", "soft natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "ethereal beauty", "pure and elegant"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, tan, sun-kissed, dark skin, explicit, pornographic, vulgar"
}
