# Auto-generated by convert_json_to_presets_v2.py
# 描述: 哥特暗黑

PRESET = {
    "name": "beauty_style_哥特暗黑",
    "description": "哥特暗黑",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful gothic woman", "dark makeup", "black lace dress", "corset", "choker"],
        "scene": ["pale skin", "dramatic shadows", "cemetery or cathedral background", "mysterious atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["elegant darkness", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, bright, colorful"
}
