# Auto-generated by convert_json_to_presets_v2.py
# 描述: 日系盐系

PRESET = {
    "name": "handsome_日系盐系",
    "description": "日系盐系",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a handsome Japanese man", "clean and fresh look", "natural style"],
        "scene": ["casual clothes", "soft lighting", "urban background", "gentle smile"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, flashy"
}
