# Auto-generated by convert_json_to_presets_v2.py
# 描述: 阳光型男

PRESET = {
    "name": "handsome_阳光型男",
    "description": "阳光型男",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a handsome young man", "sunny smile", "bright eyes", "clean-cut", "athletic build"],
        "scene": ["wearing casual white t-shirt and jeans", "standing in a park", "natural sunlight"],
        "style": [],
        "lighting": [],
        "quality": ["full body shot", "friendly expression", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, beard, unshaven, dark"
}
