# Auto-generated by convert_json_to_presets_v2.py
# 描述: 韩系欧巴

PRESET = {
    "name": "handsome_韩系欧巴",
    "description": "韩系欧巴",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a handsome Korean man", "flawless skin", "stylish haircut", "wearing fashionable Korean clothing"],
        "scene": ["city street background", "soft lighting", "full body shot"],
        "style": [],
        "lighting": [],
        "quality": ["cool expression", "trendy", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, unfashionable"
}
