# Auto-generated by convert_json_to_presets_v2.py
# 描述: 成熟绅士

PRESET = {
    "name": "handsome_成熟绅士",
    "description": "成熟绅士",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a distinguished mature gentleman", "sophisticated", "wearing a tailored suit", "confident posture", "salt and pepper hair"],
        "scene": ["piercing eyes", "in a luxury setting", "dramatic lighting"],
        "style": [],
        "lighting": [],
        "quality": ["half body shot", "elegant", "refined"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, casual, young"
}
