# Auto-generated by convert_json_to_presets_v2.py
# 描述: 古风侠客

PRESET = {
    "name": "handsome_古风侠客",
    "description": "古风侠客",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a handsome Chinese swordsman", "wearing traditional Hanfu", "long hair tied up", "holding a sword"],
        "scene": ["standing on a mountain peak", "misty background", "heroic aura"],
        "style": [],
        "lighting": [],
        "quality": ["cinematic lighting", "full body shot", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, modern clothes"
}
