# Auto-generated by convert_json_to_presets_v2.py
# 描述: 职场精英

PRESET = {
    "name": "handsome_职场精英",
    "description": "职场精英",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a handsome professional man", "wearing tailored suit", "tie", "confident posture"],
        "scene": ["modern office background", "city view", "professional atmosphere"],
        "style": [],
        "lighting": [],
        "quality": ["half body shot", "successful", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, casual, messy"
}
