# Auto-generated by convert_json_to_presets_v2.py
# 描述: 文艺青年

PRESET = {
    "name": "handsome_文艺青年",
    "description": "文艺青年",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a handsome artistic man", "intellectual", "wearing vintage glasses"],
        "scene": ["sweater", "holding a book or guitar", "cozy cafe or library background", "soft lighting"],
        "style": [],
        "lighting": [],
        "quality": ["thoughtful expression", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, jock, uneducated"
}
