# Auto-generated by convert_json_to_presets_v2.py
# 描述: 欧美硬汉

PRESET = {
    "name": "handsome_欧美硬汉",
    "description": "欧美硬汉",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a rugged Western man", "strong jaw", "stubble", "intense blue eyes", "muscular build"],
        "scene": ["wearing leather jacket", "urban night background", "dramatic lighting"],
        "style": [],
        "lighting": [],
        "quality": ["masculine", "high quality", "detailed face"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, clean-shaven, soft"
}
