# Auto-generated by convert_json_to_presets_v2.py
# 描述: 肌肉猛男

PRESET = {
    "name": "handsome_肌肉猛男",
    "description": "肌肉猛男",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a muscular man", "ripped body", "huge biceps", "six-pack abs", "defined chest"],
        "scene": ["gym lighting", "sweating", "intense look", "full body shot"],
        "style": [],
        "lighting": [],
        "quality": ["powerful physique", "bodybuilding", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, fat, skinny, weak"
}
