# Auto-generated by convert_json_to_presets_v2.py
# 描述: 运动型男

PRESET = {
    "name": "handsome_运动型男",
    "description": "运动型男",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a handsome athletic man", "sporty", "wearing jersey", "sweating"],
        "scene": ["action pose", "basketball court or gym background", "energetic"],
        "style": [],
        "lighting": [],
        "quality": ["dynamic lighting", "full body shot", "high quality"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, lazy, unmotivated"
}
