# Auto-generated by convert_json_to_presets_v2.py
# 描述: 山水画

PRESET = {
    "name": "landscape_山水画",
    "description": "山水画",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "breathtaking landscape", "majestic mountains", "misty peaks", "flowing river", "ancient pine trees"],
        "scene": ["traditional Chinese painting style", "ink wash", "artistic composition"],
        "style": [],
        "lighting": [],
        "quality": ["serene atmosphere", "high quality", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, modern buildings, pollution"
}
