# Auto-generated by convert_json_to_presets_v2.py
# 描述: 海边日落

PRESET = {
    "name": "landscape_海边日落",
    "description": "海边日落",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "stunning beach sunset", "golden sun sinking into the ocean", "warm orange and pink sky", "gentle waves"],
        "scene": ["palm trees silhouette", "tropical paradise", "romantic atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["photorealistic", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, cloudy, rainy, dark"
}
