# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雪山之巅

PRESET = {
    "name": "landscape_雪山之巅",
    "description": "雪山之巅",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "majestic snow-capped mountains", "pristine white peaks", "clear blue sky", "alpine scenery"],
        "scene": ["dramatic clouds", "high altitude atmosphere", "breathtaking view", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["photorealistic", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, pollution, urban"
}
