# Auto-generated by convert_json_to_presets_v2.py
# 描述: 森林秘境

PRESET = {
    "name": "landscape_森林秘境",
    "description": "森林秘境",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "magical forest", "sunlight filtering through dense canopy", "green moss", "ancient trees", "wild flowers"],
        "scene": ["mysterious atmosphere", "ethereal lighting", "fantasy forest"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed", "nature photography"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, deforested, barren"
}
