# Auto-generated by convert_json_to_presets_v2.py
# 描述: 城市夜景

PRESET = {
    "name": "landscape_城市夜景",
    "description": "城市夜景",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "beautiful city night view", "skyscrapers with bright lights", "neon signs", "bustling streets"],
        "scene": ["starry sky", "long exposure photography", "vibrant nightlife", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "urban atmosphere"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, daytime, dull"
}
