# Auto-generated by convert_json_to_presets_v2.py
# 描述: 极光之夜

PRESET = {
    "name": "landscape_极光之夜",
    "description": "极光之夜",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "stunning aurora borealis", "colorful northern lights dancing in the sky", "starry night", "snow-covered landscape"],
        "scene": ["magical atmosphere", "high quality", "photorealistic"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "breathtaking"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, cloudy, daytime"
}
