# Auto-generated by convert_json_to_presets_v2.py
# 描述: 田园风光

PRESET = {
    "name": "landscape_田园风光",
    "description": "田园风光",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "beautiful countryside", "rolling green hills", "golden wheat fields", "charming farmhouse", "wildflowers"],
        "scene": ["peaceful rural landscape", "warm sunlight", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["photorealistic", "detailed", "serene"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, urban, industrial"
}
