# Auto-generated by convert_json_to_presets_v2.py
# 描述: 樱花大道

PRESET = {
    "name": "landscape_樱花大道",
    "description": "樱花大道",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "beautiful cherry blossom avenue", "pink petals falling like snow", "sunlight filtering through blossoms", "Japanese scenery"],
        "scene": ["spring atmosphere", "romantic", "high quality", "photorealistic"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "dreamy"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, autumn, winter"
}
