# Auto-generated by convert_json_to_presets_v2.py
# 描述: 自然融合裸体

PRESET = {
    "name": "nude_art_自然融合裸体",
    "description": "自然融合裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman merged with nature", "naked body covered in flowers and vines", "forest background", "dappled sunlight", "mystical atmosphere"],
        "scene": ["artistic nude photography", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["ethereal", "masterpiece", "natural beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
