# Auto-generated by convert_json_to_presets_v2.py
# 描述: 情侣躺卧（裸）

PRESET = {
    "name": "nude_couple_情侣躺卧_裸",
    "description": "情侣躺卧（裸）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a man and woman lying together", "naked", "intimate cuddling"],
        "scene": ["nude couple", "soft morning light", "cozy bed", "sensual yet artistic"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
