# Auto-generated by convert_json_to_presets_v2.py
# 描述: 法国美女（裸体）

PRESET = {
    "name": "nude_other_法国美女_裸体",
    "description": "法国美女（裸体）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful French woman", "elegant", "sophisticated", "pale skin", "slim figure", "natural breasts", "naked"],
        "scene": ["sensual pose", "Parisian apartment", "soft natural light", "intimate atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "timeless elegance", "artistic nude"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
