# Auto-generated by convert_json_to_presets_v2.py
# 描述: 日本美女（裸体）

PRESET = {
    "name": "nude_other_日本美女_裸体",
    "description": "日本美女（裸体）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Japanese woman", "flawless skin", "dark hair", "elegant", "naked", "traditional Japanese garden"],
        "scene": ["cherry blossoms", "soft lighting", "artistic nude", "intimate atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "graceful beauty", "serene and sensual"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
