# Auto-generated by convert_json_to_presets_v2.py
# 描述: 威尼斯画派裸体

PRESET = {
    "name": "nude_other_威尼斯画派裸体",
    "description": "威尼斯画派裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "venetian school", "a beautiful European woman", "classical nude", "warm golden lighting", "rich colors", "velvet fabrics"],
        "scene": ["elegant pose", "Venetian background", "fine art", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "masterpiece", "titian style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
