# Auto-generated by convert_json_to_presets_v2.py
# 描述: 火与影裸体

PRESET = {
    "name": "nude_art_火与影裸体",
    "description": "火与影裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman with dramatic fire and shadow", "nude body", "glowing embers", "moody lighting", "artistic fine art photography"],
        "scene": ["high contrast", "emotional atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "masterpiece", "intense and passionate"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, fire hazard, burning, flames"
}
