# Auto-generated by convert_json_to_presets_v2.py
# 描述: 运动力量裸体

PRESET = {
    "name": "nude_other_运动力量裸体",
    "description": "运动力量裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful athletic woman", "naked", "defined muscles", "powerful pose"],
        "scene": ["gym or training background", "natural lighting", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "strength and grace", "fitness"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
