# Auto-generated by convert_json_to_presets_v2.py
# 描述: 水墨画裸体

PRESET = {
    "name": "nude_art_水墨画裸体",
    "description": "水墨画裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "ink wash painting style", "traditional Chinese art", "a beautiful Asian woman", "artistic nude", "flowing brush strokes"],
        "scene": ["minimalistic", "elegant", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "timeless beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
