# Auto-generated by convert_json_to_presets_v2.py
# 描述: 古典背影裸体

PRESET = {
    "name": "nude_other_古典背影裸体",
    "description": "古典背影裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "classical art", "a beautiful European woman", "nude from behind", "elegant back view", "soft warm lighting", "long flowing hair"],
        "scene": ["classical background", "fine art", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "timeless beauty", "artistic composition"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
