# Auto-generated by convert_json_to_presets_v2.py
# 描述: 韩国美女（裸体）

PRESET = {
    "name": "nude_other_韩国美女_裸体",
    "description": "韩国美女（裸体）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Korean woman", "flawless skin", "perfect body", "natural breasts", "naked"],
        "scene": ["Seoul city view", "modern apartment", "soft lighting", "artistic nude"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "elegant and trendy"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
