# Auto-generated by convert_json_to_presets_v2.py
# 描述: 古典躺卧裸体

PRESET = {
    "name": "nude_couple_古典躺卧裸体",
    "description": "古典躺卧裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "classical art", "a beautiful European woman", "reclining nude", "soft warm lighting", "elegant pose", "luxurious fabrics"],
        "scene": ["classical background", "fine art", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "venus style", "timeless beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
