# Auto-generated by convert_json_to_presets_v2.py
# 描述: 私处特写（艺术）

PRESET = {
    "name": "nude_private_私处特写_艺术",
    "description": "私处特写（艺术）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "artistic nude photography", "close-up of a woman's lower body", "intimate area", "soft focus", "beautiful lighting"],
        "scene": ["elegant composition", "fine art", "tasteful nudity", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "natural beauty", "gentle curves"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, extreme closeup, gore, blood, injury, medical, surgery, disease, infection, shaved"
}
