# Auto-generated by convert_json_to_presets_v2.py
# 描述: 表现主义裸体

PRESET = {
    "name": "nude_art_表现主义裸体",
    "description": "表现主义裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "expressionism style", "a beautiful woman", "artistic nude", "emotional brushstrokes", "vivid colors"],
        "scene": ["dramatic composition", "fine art", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "expressive"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
