# Auto-generated by convert_json_to_presets_v2.py
# 描述: 纯白大理石艺术裸体

PRESET = {
    "name": "nude_other_纯白大理石艺术裸体",
    "description": "纯白大理石艺术裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman as a pure white marble nude statue", "classical sculpture", "artistic nude", "flawless white stone", "elegant pose", "museum display"],
        "scene": ["dramatic lighting", "monochrome white", "intricate carving details"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "photorealistic", "fine art"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, color, skin tone, warm tones, beige, yellow, gray, painting, cartoon, 3d render, shiny, glossy, wet, oil, plastic, wax, explicit, pornographic"
}
