# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巴西大胸裸体

PRESET = {
    "name": "nude_other_巴西大胸裸体",
    "description": "巴西大胸裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Brazilian woman with huge natural breasts", "big boobs", "naked", "flawless tan skin", "elegant Latin features"],
        "scene": ["soft warm lighting", "full body shot", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "curvy body", "sensual and artistic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat chest, small chest"
}
