# Auto-generated by convert_json_to_presets_v2.py
# 描述: 水镜倒影裸体

PRESET = {
    "name": "nude_art_水镜倒影裸体",
    "description": "水镜倒影裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman in water", "naked body", "water reflections", "mirror-like surface", "serene atmosphere", "artistic nude photography"],
        "scene": ["soft lighting", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["ethereal", "masterpiece", "peaceful beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar"
}
