# Auto-generated by convert_json_to_presets_v2.py
# 描述: 私处特写（花丛）

PRESET = {
    "name": "nude_private_私处特写_花丛",
    "description": "私处特写（花丛）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "beautiful woman's intimate area surrounded by flowers", "artistic composition", "soft natural lighting", "flower petals", "feminine beauty"],
        "scene": ["tasteful nude", "fine art photography", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "dreamy atmosphere", "romantic"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, extreme closeup, gore, blood, injury, medical, surgery, disease, infection"
}
