# Auto-generated by convert_json_to_presets_v2.py
# 描述: 巴洛克裸体

PRESET = {
    "name": "nude_other_巴洛克裸体",
    "description": "巴洛克裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "baroque style", "a beautiful European woman", "classical nude", "dramatic chiaroscuro lighting", "rich dark background", "elegant pose"],
        "scene": ["luxurious fabrics", "fine art", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "masterpiece", "old masters style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
