# Auto-generated by convert_json_to_presets_v2.py
# 描述: 新古典主义裸体

PRESET = {
    "name": "nude_other_新古典主义裸体",
    "description": "新古典主义裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "neoclassical style", "a beautiful European woman", "classical nude", "soft lighting", "marble background", "elegant pose"],
        "scene": ["ancient Greek inspiration", "fine art", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "masterpiece", "timeless beauty"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
