# Auto-generated by convert_json_to_presets_v2.py
# 描述: 洛可可裸体

PRESET = {
    "name": "nude_other_洛可可裸体",
    "description": "洛可可裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "rococo style", "a beautiful European woman", "classical nude", "soft pastel colors", "elegant pose", "luxurious boudoir"],
        "scene": ["ornate background", "fine art", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["masterpiece", "feminine beauty", "18th century style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
