# Auto-generated by convert_json_to_presets_v2.py
# 描述: 意大利美女（裸体）

PRESET = {
    "name": "nude_other_意大利美女_裸体",
    "description": "意大利美女（裸体）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a beautiful Italian woman", "olive skin", "dark hair", "sensual curves", "full breasts", "round buttocks", "naked"],
        "scene": ["Mediterranean villa background", "warm golden lighting", "artistic nude", "intimate atmosphere", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed face", "passionate beauty", "timeless elegance"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, heavy makeup, explicit, pornographic, vulgar"
}
