# Auto-generated by convert_json_to_presets_v2.py
# 描述: 剪影艺术

PRESET = {
    "name": "nude_art_剪影艺术",
    "description": "剪影艺术",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "a beautiful woman in dramatic silhouette", "backlighting", "sunset or golden hour", "naked body outlined by light", "elegant pose", "artistic composition"],
        "scene": ["high contrast", "emotional atmosphere", "fine art photography"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed", "breathtaking"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, explicit, pornographic, vulgar"
}
