# Auto-generated by convert_json_to_presets_v2.py
# 描述: 文艺复兴裸体

PRESET = {
    "name": "nude_other_文艺复兴裸体",
    "description": "文艺复兴裸体",
    "layers": {
        "subject": ["masterpiece", "best quality", "oil painting", "renaissance style", "a beautiful European woman", "classical nude", "soft lighting", "warm skin tones", "rich colors", "elegant pose"],
        "scene": ["velvet drapery", "renaissance background", "fine art", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "timeless beauty", "classical painting style"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, cartoon, anime, modern, photography, photorealistic, 3d render, explicit, pornographic"
}
