# Auto-generated by convert_json_to_presets_v2.py
# 描述: 美国美女（裸体）

PRESET = {
    "name": "nude_other_美国美女_裸体",
    "description": "美国美女（裸体）",
    "layers": {
        "subject": ["masterpiece", "best quality", "photorealistic", "8k", "a stunning American woman", "tan skin", "fit body", "large breasts", "big round buttocks", "naked"],
        "scene": ["Miami beach background", "golden sunset", "full body shot", "artistic nude", "summer vibe"],
        "style": [],
        "lighting": [],
        "quality": ["high quality", "detailed face", "confident and gorgeous"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, bad anatomy, bad hands, missing fingers, extra digits, watermark, text, signature, explicit, pornographic, vulgar, flat butt, small chest"
}
