# Auto-generated by convert_json_to_presets_v2.py
# 描述: 雨后荷花

PRESET = {
    "name": "plant_雨后荷花",
    "description": "雨后荷花",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "lotus flowers after rain", "water droplets on pink petals", "peaceful pond", "green lily pads"],
        "scene": ["soft misty atmosphere", "Chinese painting style", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "serene"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, polluted water"
}
