# Auto-generated by convert_json_to_presets_v2.py
# 描述: 玫瑰花海

PRESET = {
    "name": "plant_玫瑰花海",
    "description": "玫瑰花海",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "vast rose garden", "blooming red roses", "morning dew on petals", "soft sunlight"],
        "scene": ["romantic atmosphere", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["nature photography", "beautiful flowers"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, dead, wilted"
}
