# Auto-generated by convert_json_to_presets_v2.py
# 描述: 樱花满开

PRESET = {
    "name": "plant_樱花满开",
    "description": "樱花满开",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "cherry blossoms in full bloom", "pink flowers covering branches", "soft petals falling", "spring atmosphere"],
        "scene": ["Japanese scenery", "beautiful nature", "high quality"],
        "style": [],
        "lighting": [],
        "quality": ["photorealistic", "detailed"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, autumn, winter"
}
