# Auto-generated by convert_json_to_presets_v2.py
# 描述: 日本枫叶

PRESET = {
    "name": "plant_日本枫叶",
    "description": "日本枫叶",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "beautiful autumn leaves", "vibrant red and orange maple leaves", "sunlight filtering through", "Japanese garden"],
        "scene": ["peaceful atmosphere", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["nature photography", "fall season"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, spring, summer"
}
