# Auto-generated by convert_json_to_presets_v2.py
# 描述: 竹林幽径

PRESET = {
    "name": "plant_竹林幽径",
    "description": "竹林幽径",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "serene bamboo forest", "tall green bamboo stalks", "sunlight filtering through leaves", "peaceful path"],
        "scene": ["traditional Asian atmosphere", "high quality", "detailed"],
        "style": [],
        "lighting": [],
        "quality": ["nature photography", "tranquil"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, urban, noisy"
}
