# Auto-generated by convert_json_to_presets_v2.py
# 描述: 梦幻薰衣草

PRESET = {
    "name": "plant_梦幻薰衣草",
    "description": "梦幻薰衣草",
    "layers": {
        "subject": ["masterpiece", "best quality", "8k", "endless lavender fields", "purple flowers stretching to the horizon", "soft lighting", "Provence atmosphere"],
        "scene": ["romantic", "high quality", "photorealistic"],
        "style": [],
        "lighting": [],
        "quality": ["detailed", "dreamy landscape"],
    },
    "negative": "worst quality, low quality, ugly, deformed, blurry, watermark, text, signature, winter, bare"
}
