# Auto-generated by convert_json_to_presets_v2.py
# 描述: 从 scenes.json 转换而来

PRESET = {
    "name": "scenes",
    "description": "从 scenes.json 转换而来",
    "layers": {
        "subject": ["high quality, detailed", "photorealistic, real photo, 8k, ultra HD, highly detailed", "artistic, painting style, masterpiece", "anime style, manga, Japanese animation", "cinematic lighting, movie still, film grain", "portrait photography, professional, bokeh background", "fashion photography, editorial, glamorous", "full body shot, entire body visible", "half body shot, from waist up", "headshot, face only", "close up, detailed view", "wide shot, establishing shot", "eye level shot", "low angle shot, looking up", "high angle shot, looking down"],
        "scene": ["indoors, interior setting", "outdoors, exterior, open air", "studio photography, professional backdrop, seamless background", "bedroom, cozy atmosphere, soft lighting, bed", "living room, comfortable home setting, sofa", "kitchen, cooking area, modern appliances", "office, professional environment, desk, computer", "beach, sand, ocean, waves, seaside", "park, green grass, trees, nature, sunny", "city street, urban background, buildings, sidewalk", "restaurant, dining setting, tables, romantic atmosphere", "cafe, coffee shop, cozy interior, coffee cups", "gym, fitness center, workout equipment", "swimming pool, water, lounge chairs", "forest, trees, woods, natural setting, sunlight through leaves", "mountain, scenic view, landscape", "garden, flowers, plants, beautiful landscaping", "school, classroom, educational setting", "hospital, medical setting, clean", "wedding venue, ceremony, romantic decoration", "party, celebration, festive atmosphere"],
        "style": [],
        "lighting": ["natural lighting, daylight, soft sunlight", "warm lighting, golden hour, cozy", "cold lighting, blue tone, clinical", "dramatic lighting, strong shadows, contrast", "soft lighting, diffused, gentle", "neon lighting, cyberpunk, colorful", "studio lighting, professional, well-lit", "candlelight, romantic, flickering", "sunset lighting, golden, warm glow", "night lighting, dark, street lamps"],
        "quality": [],
    },
    "negative": ""
}
