# safe_dump.py
"""安全、干净的代码打包脚本 (终极版)"""
import os
from pathlib import Path

# 项目根目录和输出文件路径
PROJECT_ROOT = Path(r"E:\SD_OpenVINO\ForgeWorkspace")
OUTPUT_FILE = PROJECT_ROOT / "project_code_dump.txt"

# 必须排除的目录 (防止打包垃圾和构建产物)
EXCLUDE_DIRS = {
    ".git", "__pycache__", "node_modules", "venv", ".venv", "env", 
    "models", "data", "shared_assets", "output", "outputs", 
    "build", "dist", "temp_gather", "logs", ".idea", ".vscode",
    "flutter_assets", "intermediates", ".gradle"
}

# 允许打包的文件扩展名 (仅限代码和配置)
ALLOWED_EXTS = {
    ".py", ".txt", ".json", ".env", ".md", ".yml", ".yaml",
    ".cfg", ".conf", ".xml", ".html", ".css", ".js", 
    ".gitignore", ".dockerignore", ".editorconfig", ".toml"
}

def main():
    print("=" * 70)
    print(f"🚀 开始安全打包 ForgeWorkspace 代码到: {OUTPUT_FILE.name}")
    print("=" * 70 + "\n")
    
    file_count = 0
    total_size = 0
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f_out:
        f_out.write(f"=== Project Dump: {PROJECT_ROOT.name} ===\n")
        f_out.write(f"Generated by safe_dump.py\n\n")
        
        for root, dirs, files in os.walk(PROJECT_ROOT):
            # 1. 强制过滤掉不需要进入的目录 (原地修改 dirs，os.walk 就不会再深入)
            dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS]
            
            for file in files:
                file_path = Path(root) / file
                
                # 2. 只保留允许的扩展名
                if file_path.suffix.lower() not in ALLOWED_EXTS:
                    continue
                
                # 3. 双重保险：检查文件大小 (超过 500KB 的文件直接跳过，防止大日志或数据库)
                try:
                    if file_path.stat().st_size > 500 * 1024: 
                        continue
                except OSError:
                    continue
                
                # 4. 读取并写入文本
                try:
                    content = file_path.read_text(encoding="utf-8")
                    rel_path = file_path.relative_to(PROJECT_ROOT)
                    
                    # 写入分隔符和文件路径
                    f_out.write(f"\n{'='*70}\n")
                    f_out.write(f"FILE: {rel_path.as_posix()}\n")
                    f_out.write(f"{'='*70}\n\n")
                    f_out.write(content)
                    f_out.write("\n")
                    
                    file_count += 1
                    total_size += len(content.encode('utf-8'))
                except Exception:
                    # 忽略无法以 UTF-8 读取的二进制文件
                    pass
                    
    print(f"✅ 打包完成！")
    print(f"📊 共处理了 {file_count} 个代码/配置文件。")
    print(f"📄 输出文件已保存至: {OUTPUT_FILE}")
    print(f"💡 提示：文件大小约为 {total_size / 1024 / 1024:.2f} MB，绝对安全，不含任何模型！")
    print("=" * 70)

if __name__ == "__main__":
    main()